// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// --------- //
// cansample //
// --------- //

#define cansample_wrap_target 0
#define cansample_wrap 0
#define cansample_pio_version 0

static __pio_const uint16_t cansample_program_instructions[] = {
            //     .wrap_target
    0x4001, //  0: in     pins, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program cansample_program = {
    .instructions = cansample_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = cansample_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config cansample_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cansample_wrap_target, offset + cansample_wrap);
    return c;
}
#endif

