// GENERATED by 'make boards' from the firmware ELFs -- do not edit.
// system = statics - arena: the core plus every linked library, i.e.
// what is taken BEFORE CandySpeak claims what is left. Re-run after
// changing which libraries a sketch links in.
#ifndef __CSP_BOARDS_H__
#define __CSP_BOARDS_H__

/* mega: statics 7256 = system 2701 + state 459 + arena 4096 */
#define CSP_BOARD_MEGA_RAM     8192
#define CSP_BOARD_MEGA_SYSTEM  2701
#define CSP_BOARD_MEGA_STATE   459   /* target sizeof(csp_rt_t): 16/32-bit, smaller than the 64-bit host */
#define CSP_BOARD_MEGA_EEPROM  4096

/* mkrzero: statics 16552 = system 3128 + state 1136 + arena 12288 */
#define CSP_BOARD_MKRZERO_RAM     32768
#define CSP_BOARD_MKRZERO_SYSTEM  3128
#define CSP_BOARD_MKRZERO_STATE   1136   /* target sizeof(csp_rt_t): 16/32-bit, smaller than the 64-bit host */
#define CSP_BOARD_MKRZERO_EEPROM  2048

/* play: statics 16552 = system 3128 + state 1136 + arena 12288 */
#define CSP_BOARD_PLAY_RAM     32768
#define CSP_BOARD_PLAY_SYSTEM  7325
#define CSP_BOARD_PLAY_STATE   1152
#define CSP_BOARD_PLAY_EEPROM  2048

#endif
