// generated by utils/gen_tables.erl from utils/syntax.terms -- do not edit
//
// The scanner's tokens and the declaration keywords: each enum together
// with the table its members index. Edit the terms, run `make tables`.
#ifndef __CSP_TOKENS_H__
#define __CSP_TOKENS_H__

typedef enum {
    NONE = 0,
    NEWLINE,
    LP,
    RP,
    COLON,
    HASH,
    DOT,
    DOTDOT,
    LB,
    RB,
    LBRACE,
    RBRACE,
    INT,
    FLT,
    STR,
    EXCLAMATION,
    TILDE,
    MINUS1,
    PLUS1,
    PLUS,
    MINUS,
    ASTERISK,
    SLASH,
    PERCENT,
    LTLT,
    GTGT,
    LT,
    LTEQ,
    GT,
    GTEQ,
    EQEQ,
    NEQ,
    AMP,
    BAR,
    CIRC,
    AMPAMP,
    BARBAR,
    EQ,
    RIMP,
    COMMA,
    QUEST,
    WORD,
    T_PULLUP,
    T_PULLDOWN,
    T_RESOLUTION,
    T_IN,
    T_OUT,
    T_INOUT,
    T_PWM,
    T_FLOAT,
    T_INTEGER,
    T_UNSIGNED,
    T_STRING,
    T_NATIVE,
    T_LITTLE,
    T_BIG,
    T_CAN,
    T_DISABLE,
    T_ENABLE,
    T_LAST,
} tok_t;

typedef enum {
    D_NONE = 0,
    D_MODULE,
    D_END,
    D_STATES,
    D_IN,
    D_CONSTANT,
    D_VARIABLE,
    D_LOCAL,
    D_DIGITAL,
    D_ANALOG,
    D_TIMER,
    D_FIELD,
    D_BUFFER,
    D_UART,
    D_SOCKET,
    D_MOD,
    D_LAST,
} dtok_t;

#define CSP_TOK_TABLE \
    INSTR_ENT(NONE,OP_NOP,s_NOP,-1,0,NO), \
    TOK_ENT(NEWLINE,OP_NOP,s_null), \
    TOK_ENT(LP,OP_NOP,s_LP), \
    TOK_ENT(RP,OP_NOP,s_RP), \
    TOK_ENT(COLON,OP_NOP,s_COLON), \
    TOK_ENT(HASH,OP_NOP,s_HASH), \
    TOK_ENT(DOT,OP_NOP,s_DOT), \
    TOK_ENT(DOTDOT,OP_NOP,s_DOTDOT), \
    TOK_ENT(LB,OP_NOP,s_LB), \
    TOK_ENT(RB,OP_NOP,s_RB), \
    TOK_ENT(LBRACE,OP_NOP,s_LBRACE), \
    TOK_ENT(RBRACE,OP_NOP,s_RBRACE), \
    TOK_ENT(INT,OP_NOP,s_null), \
    TOK_ENT(FLT,OP_NOP,s_null), \
    TOK_ENT(STR,OP_NOP,s_null), \
    INSTR_ENT(EXCLAMATION,OP_NOT,s_EXCLAMATION,1,105,RIGHT), \
    INSTR_ENT(TILDE,OP_BNOT,s_TILDE,1,105,RIGHT), \
    INSTR_ENT(MINUS1,OP_NEG,s_MINUS,1,105,RIGHT), \
    INSTR_ENT(PLUS1,OP_MOV,s_MOV,1,105,RIGHT), \
    INSTR_ENT(PLUS,OP_ADD,s_PLUS,2,90,LEFT), \
    INSTR_ENT(MINUS,OP_SUB,s_MINUS,2,90,LEFT), \
    INSTR_ENT(ASTERISK,OP_MUL,s_ASTERISK,2,100,LEFT), \
    INSTR_ENT(SLASH,OP_DIV,s_SLASH,2,100,LEFT), \
    INSTR_ENT(PERCENT,OP_REM,s_PERCENT,2,100,LEFT), \
    INSTR_ENT(LTLT,OP_SLA,s_LTLT,2,80,LEFT), \
    INSTR_ENT(GTGT,OP_SRA,s_GTGT,2,80,LEFT), \
    INSTR_ENT(LT,OP_LT,s_LT,2,70,LEFT), \
    INSTR_ENT(LTEQ,OP_LTE,s_LTEQ,2,70,LEFT), \
    INSTR_ENT(GT,OP_GT,s_GT,2,70,LEFT), \
    INSTR_ENT(GTEQ,OP_GTE,s_GTEQ,2,70,LEFT), \
    INSTR_ENT(EQEQ,OP_EQEQ,s_EQEQ,2,60,LEFT), \
    INSTR_ENT(NEQ,OP_NEQ,s_NEQ,2,60,LEFT), \
    INSTR_ENT(AMP,OP_BAND,s_AMP,2,50,LEFT), \
    INSTR_ENT(BAR,OP_BOR,s_BAR,2,30,LEFT), \
    INSTR_ENT(CIRC,OP_BXOR,s_CIRC,2,40,LEFT), \
    INSTR_ENT(AMPAMP,OP_AND,s_AMPAMP,2,20,LEFT), \
    INSTR_ENT(BARBAR,OP_OR,s_BARBAR,2,10,LEFT), \
    INSTR_ENT(EQ,OP_EQ,s_EQ,2,5,RIGHT), \
    INSTR_ENT(RIMP,OP_RIMP,s_RIMP,2,4,RIGHT), \
    INSTR_ENT(COMMA,OP_NOP,s_COMMA,2,2,RIGHT), \
    TOK_ENT(QUEST,OP_RULE,s_QUEST), \
    TOK_ENT(WORD,OP_NOP,s_null), \
    TOK_ENT(T_PULLUP,OP_NOP,s_pullup), \
    TOK_ENT(T_PULLDOWN,OP_NOP,s_pulldown), \
    TOK_ENT(T_RESOLUTION,OP_NOP,s_resolution), \
    TOK_ENT(T_IN,OP_NOP,s_in), \
    TOK_ENT(T_OUT,OP_NOP,s_out), \
    TOK_ENT(T_INOUT,OP_NOP,s_inout), \
    TOK_ENT(T_PWM,OP_NOP,s_pwm), \
    TOK_ENT(T_FLOAT,OP_NOP,s_float), \
    TOK_ENT(T_INTEGER,OP_NOP,s_integer), \
    TOK_ENT(T_UNSIGNED,OP_NOP,s_unsigned), \
    TOK_ENT(T_STRING,OP_NOP,s_string), \
    TOK_ENT(T_NATIVE,OP_NOP,s_native), \
    TOK_ENT(T_LITTLE,OP_NOP,s_little), \
    TOK_ENT(T_BIG,OP_NOP,s_big), \
    TOK_ENT(T_CAN,OP_NOP,s_can), \
    TOK_ENT(T_DISABLE,OP_NOP,s_disable), \
    TOK_ENT(T_ENABLE,OP_NOP,s_enable), \
    TOK_ENT(T_LAST,OP_NOP,s_null),

#define CSP_DECL_TABLE \
    DECL_ENT(D_NONE,DECL_NONE,s_none), \
    DECL_ENT(D_MODULE,DECL_MODULE,s_module), \
    DECL_ENT(D_END,DECL_END,s_end), \
    DECL_ENT(D_STATES,DECL_STATES,s_states), \
    DECL_ENT(D_IN,DECL_IN,s_in), \
    DECL_ENT(D_CONSTANT,DECL_CONSTANT,s_constant), \
    DECL_ENT(D_VARIABLE,DECL_VARIABLE,s_variable), \
    DECL_ENT(D_LOCAL,DECL_VARIABLE,s_local), \
    DECL_ENT(D_DIGITAL,DECL_DIGITAL,s_digital), \
    DECL_ENT(D_ANALOG,DECL_ANALOG,s_analog), \
    DECL_ENT(D_TIMER,DECL_TIMER,s_timer), \
    DECL_ENT(D_FIELD,DECL_FIELD,s_field), \
    DECL_ENT(D_BUFFER,DECL_BUFFER,s_buffer), \
    DECL_ENT(D_LAST,DECL_NONE,s_null),

// Names for tok_name(), indexed by tok_t.
#define CSP_TOKEN_NAMES \
    "NONE", \
    "NEWLINE", \
    "LP", \
    "RP", \
    "COLON", \
    "HASH", \
    "DOT", \
    "DOTDOT", \
    "LB", \
    "RB", \
    "LBRACE", \
    "RBRACE", \
    "INT", \
    "FLT", \
    "STR", \
    "EXCLAMATION", \
    "TILDE", \
    "MINUS1", \
    "PLUS1", \
    "PLUS", \
    "MINUS", \
    "ASTERISK", \
    "SLASH", \
    "PERCENT", \
    "LTLT", \
    "GTGT", \
    "LT", \
    "LTEQ", \
    "GT", \
    "GTEQ", \
    "EQEQ", \
    "NEQ", \
    "AMP", \
    "BAR", \
    "CIRC", \
    "AMPAMP", \
    "BARBAR", \
    "EQ", \
    "RIMP", \
    "COMMA", \
    "QUEST", \
    "WORD", \
    "T_PULLUP", \
    "T_PULLDOWN", \
    "T_RESOLUTION", \
    "T_IN", \
    "T_OUT", \
    "T_INOUT", \
    "T_PWM", \
    "T_FLOAT", \
    "T_INTEGER", \
    "T_UNSIGNED", \
    "T_STRING", \
    "T_NATIVE", \
    "T_LITTLE", \
    "T_BIG", \
    "T_CAN", \
    "T_DISABLE", \
    "T_ENABLE", \
    "T_LAST",

#endif
