# build of csp - candy speak

CC = gcc

# Version stamped into generated ROMs (-C). A tag if there is one, else a short
# hash with -dirty when the tree has uncommitted changes; "unknown" off git.
CSP_VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo unknown)

# CSP_ARENA_MALLOC: claim the pool from the heap, sized to the simulated board
# (-M/-U/--board), instead of a fixed static array -- so the host can model a
# board with more RAM than the compile-time CSP_CODE_BUDGET.
CFLAGS=-MMD -MP -MF .$<.d -DCSP_VERSION='"$(CSP_VERSION)"' -DCSP_ARENA_MALLOC
OBJS = csp_linux.o csp_rt.o csp_repl.o csp_compile.o csp_dump.o csp_eeprom.o \
	csp_parse.o csp_print.o csp_strings.o rom.o

LIBS =

# -O3 -std=c99
CFLAGS += -Wall -g -Wdeclaration-after-statement -Wenum-compare -Wenum-conversion -Wswitch
LDFLAGS = -g

# `make ubsan` / `make san` fill SAN with these for a host build (targets below).
SAN =
SANFLAGS = -fsanitize=undefined,address -fno-omit-frame-pointer -O0
CFLAGS  += $(SAN)
LDFLAGS += $(SAN)

all:	csp

debug: CFLAGS += -DDEBUG
debug: all

# Sanitizer build (host): catches misaligned access -- the Cortex-M0 HardFault
# class that x86 tolerates silently -- plus out-of-bounds and other UB. Forces a
# clean rebuild so every object carries the flags. Then run e.g.:
#   UBSAN_OPTIONS=halt_on_error=0 ./csp examples/cpx.csp
ubsan:
	$(MAKE) clean
	$(MAKE) all SAN='$(SANFLAGS)'

# One-shot sanitizer check: clean rebuild with UBSan+ASan, run the whole unit
# suite (seq + the reactive-marked variants) under it, then restore a normal
# binary so leftover sanitized objects never break the next plain `make`.
san:
	$(MAKE) clean
	$(MAKE) all SAN='$(SANFLAGS)'
	ASAN_OPTIONS=detect_leaks=0 $(MAKE) test
	$(MAKE) clean
	$(MAKE) all

csp:	$(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) $(LIBS) -o $@

# String table: a small C tool generates csp_strings.{c,h} from strings.tab.
strtab: strtab.c
	$(CC) -Wall -o $@ strtab.c

csp_strings.c csp_strings.h: strings.tab strtab
	./strtab strings.tab csp_strings.c csp_strings.h

# sources that use the shared RODATA strings need the generated header first
csp_rt.o csp_repl.o csp_compile.o csp_strings.o: csp_strings.h

clean:
	rm -f $(OBJS) strtab csp_strings.c csp_strings.h

test:	csp test_repl
	@chmod +x tests/run_tests.escript
	@cd $(CURDIR) && escript tests/run_tests.escript tests/unit

# REPL/persistence level: /list segment tags, what a /clear keeps, and whether a
# generated ROM image loads back into the firmware that links it. None of that is
# reachable from the unit suite, which only reads variables out of a state dump.
# Fast, so it runs as part of `make test` -- unlike test_crc_destroyer.
test_repl: csp
	@bash tests/repl.sh

test-examples: csp
	@chmod +x tests/run_tests.escript
	@cd $(CURDIR) && escript tests/run_tests.escript examples

# CRC destroyer: flip bits across a saved EEPROM image under ASan/UBSan and prove
# every corrupted load is handled gracefully (restore / reject / recover) and
# NEVER crashes. Slow (rebuilds sanitized, forks per corruption) -- NOT part of
# `make test`. 1-bit is exhaustive; multi-bit sampled. Tune with:
#   CRC_MAX1=<n> CRC_MULTI=<n> make test_crc_destroyer
test_crc_destroyer:
	@chmod +x tests/crc_destroyer.sh
	@bash tests/crc_destroyer.sh

%.o:	%.c
	$(CC) $(CFLAGS) -c -fPIC $<

.%.d:	;

-include .*.d

.PHONY: all clean test test-examples test_repl test_crc_destroyer debug ubsan san

# Regenerate csp_boards.h from the firmware builds, so --board on the host uses
# MEASURED numbers instead of hand-fed ones. Needs both boards built first
# (make -C CandySpeak -f Makefile.mega / Makefile.mkrzero).
boards:
	@{ echo "// GENERATED by 'make boards' from the firmware ELFs -- do not edit."; \
	   echo "// system = statics - arena: the core plus every linked library, i.e."; \
	   echo "// what is taken BEFORE CandySpeak claims what is left. Re-run after"; \
	   echo "// changing which libraries a sketch links in."; \
	   echo "#ifndef __CSP_BOARDS_H__"; echo "#define __CSP_BOARDS_H__"; echo; \
	   ./board_ram.sh mega 8192 4096 avr-nm \
	     CandySpeak/build/tmp.arduino.avr.mega/CandySpeak.ino.elf; echo; \
	   ./board_ram.sh mkrzero 32768 2048 arm-none-eabi-nm \
	     CandySpeak/build/arduino.samd.mkrzero/CandySpeak.ino.elf; echo; \
	   echo "#endif"; } > csp_boards.h
	@sed -n '/^\/\* /p;/^#define/p' csp_boards.h
