# build of csp - candy speak

CC = gcc

# Version stamped into generated ROMs (-C). A tag if there is one, else a short
# hash with -dirty when the tree has uncommitted changes; "unknown" off git.
CSP_VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo unknown)

# CSP_ARENA_MALLOC: claim the pool from the heap, sized to the simulated board
# (-M/-U/--board), instead of a fixed static array -- so the host can model a
# board with more RAM than the compile-time CSP_CODE_BUDGET.
CFLAGS=-MMD -MP -MF .$<.d -DCSP_VERSION='"$(CSP_VERSION)"' -DCSP_ARENA_MALLOC
# rom_host.o, NOT rom.o. `rom.c` is the DEMO image -- CandySpeak/rom.c is a
# symlink to it, so it is what a board flashes, and it changes every time you
# run `csp -C -O rom.c prog.csp`. ./csp is the compiler, the REPL and what the
# test suites run, and it must not carry somebody's program as its ROM baseline:
# with traffic.csp in there every unit test ran on top of Red/Yellow/Green and
# 45 of them "failed".
#
# rom_host.c is the neutral image (2 decls, 0 instructions -- just State and the
# runtime baseline) and is COMMITTED rather than generated by a make rule: it
# takes ./csp to produce one, and ./csp needs it to link. Regenerate it by hand
# on the rare occasion the format changes:
#
#     ./csp -n -C -O rom_host.c examples/empty.csp
#
# BUMPING ROM_FORMAT_VERSION closes that circle: the committed rom_host.c stops
# compiling ("rom.c is stale ... regenerate"), so there is no ./csp to regenerate
# it with. Break it with a one-off binary whose image is the OLD one -- csp does
# not care, that image is empty, and a version mismatch only makes it boot with
# no program:
#
#     sed 's/!= 10/!= 11/' rom_host.c > tmp/rom_boot.c     # old version -> new
#     $(CC) -DCSP_ARENA_MALLOC -I. $(CORE_SRC) tmp/rom_boot.c -o tmp/csp_boot
#     tmp/csp_boot -n -C -O rom_host.c examples/empty.csp
#     tmp/csp_boot -n -C -O rom.c      examples/cpx_rotate.csp
OBJS = csp_linux.o csp_rt.o csp_line.o csp_repl.o csp_compile.o csp_tok.o csp_dump.o csp_eeprom.o \
	csp_parse.o csp_print.o csp_strings.o csp_flash.o csp_devices.o \
	csp_flash_host.o rom_host.o

LIBS =

# -O3 -std=c99
CFLAGS += -Wall -g -Wdeclaration-after-statement -Wenum-compare -Wenum-conversion -Wswitch
LDFLAGS = -g

# `make ubsan` / `make san` fill SAN with these for a host build (targets below).
SAN =
SANFLAGS = -fsanitize=undefined,address -fno-omit-frame-pointer -O0
CFLAGS  += $(SAN)
LDFLAGS += $(SAN)

all:	csp

debug: CFLAGS += -DDEBUG
debug: all

# Sanitizer build (host): catches misaligned access -- the Cortex-M0 HardFault
# class that x86 tolerates silently -- plus out-of-bounds and other UB. Forces a
# clean rebuild so every object carries the flags. Then run e.g.:
#   UBSAN_OPTIONS=halt_on_error=0 ./csp examples/cpx.csp
ubsan:
	$(MAKE) clean
	$(MAKE) all SAN='$(SANFLAGS)'

# One-shot sanitizer check: clean rebuild with UBSan+ASan, run the whole unit
# suite (seq + the reactive-marked variants) under it, then restore a normal
# binary so leftover sanitized objects never break the next plain `make`.
san:
	$(MAKE) clean
	$(MAKE) all SAN='$(SANFLAGS)'
	ASAN_OPTIONS=detect_leaks=0 $(MAKE) test
	$(MAKE) clean
	$(MAKE) all

csp:	$(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) $(LIBS) -o $@

# --- exec-only host builds ---------------------------------------------------
# The same two tiers the boards use, built here so the guards can be checked
# without an AVR toolchain -- a missing #if shows up as a link error in seconds.
#
#   exec  CSP_EXEC_ONLY   no scanner, no parser, no REPL commands. What is left
#                         runs a linked ROM image and nothing else.
#   min   + CSP_NO_EEPROM on the HOST this changes nothing (csp_linux.c always
#                         provides the file backend); it is the board tier, kept
#                         here so both spellings compile.
#
# Separate binaries, not a rebuild of ./csp -- you want both around to compare.
# These DO link rom.c, the demo image: running a linked program is the whole
# point of the exec tier, and it is the same file the boards flash. ./csp links
# rom_host.c instead -- see the OBJS note above.
# Point them at a real program with:  ./csp -n -C -O rom.c prog.csp && make exec
#
# CORE_SRC is the same list with NO image at all -- `make rom` below appends
# whichever one it just generated.
CORE_SRC = csp_linux.c csp_rt.c csp_repl.c csp_compile.c csp_tok.c csp_dump.c \
	   csp_eeprom.c csp_parse.c csp_print.c csp_strings.c \
	   csp_flash.c csp_devices.c csp_flash_host.c
EXEC_SRC = $(CORE_SRC) rom.c
# csp_repl.c, csp_compile.c and csp_dump.c are still LISTED: each guards itself
# to an empty translation unit, so the file list stays the same as ./csp and a
# missing guard shows up as a link error rather than a silent divergence.
EXEC_FLAGS = -DCSP_VERSION='"$(CSP_VERSION)"' -DCSP_ARENA_MALLOC -Wall -g $(SAN)

exec:	csp_strings.h
	$(CC) $(EXEC_FLAGS) -DCSP_EXEC_ONLY $(EXEC_SRC) $(LIBS) -o csp-exec
	@size csp-exec 2>/dev/null | tail -1 || true

min:	csp_strings.h
	$(CC) $(EXEC_FLAGS) -DCSP_EXEC_ONLY -DCSP_NO_EEPROM $(EXEC_SRC) $(LIBS) -o csp-min
	@size csp-min 2>/dev/null | tail -1 || true

# --- a host binary carrying a PROGRAM as its firmware ROM image --------------
#
# ./csp deliberately carries none (rom_host.c is the neutral image, see the OBJS
# note), so against it there is no F tag to see, no ROM #param to override and no
# section CRC to check -- every one of those needs a program in flash. This links
# a binary that has one, the same way a board does: -C generates the image and it
# compiles in place of rom_host.c.
#
#   make rom PROG=examples/cpx_rotate.csp              -> tmp/cpx_rotate
#   make rom PROG="lib/pid.csp app.csp" OUT=tmp/demo   -> tmp/demo
#   make rom PROG=examples/blink.csp TIER=exec         -> the exec-only tier
#
# Several .csp files are read as ONE program, in order, exactly as ./csp reads
# them. OUT defaults to tmp/<first program's basename>; tmp/ is gitignored, so
# these do not accumulate in the tree the way a hand-rolled gcc line does.
#
# The generated image is kept beside the binary as <OUT>.rom.c -- when a load
# fails ("ROM rejected: CRC mismatch...") that file is the evidence. It is
# compiled with -I. because it lives wherever OUT points and #includes "csp.h",
# which gcc otherwise looks for next to the image and not here.
#
# For the BOARD, the image has to be rom.c, which CandySpeak/rom.c symlinks to:
#
#   make rom-image PROG=examples/cpx_rotate.csp
#   make -C CandySpeak -f Makefile.mega
#
PROG ?=
OUT  ?=
TIER ?=

ifeq ($(TIER),exec)
ROM_TIER = -DCSP_EXEC_ONLY
else ifeq ($(TIER),min)
ROM_TIER = -DCSP_EXEC_ONLY -DCSP_NO_EEPROM
else ifeq ($(TIER),)
ROM_TIER =
else
$(error TIER must be exec, min, or empty for the full build)
endif

# `csp` first: it is the compiler that produces the image.
rom:	csp csp_strings.h
	@test -n "$(PROG)" || { \
	    echo "usage: make rom PROG='a.csp [b.csp ...]' [OUT=name] [TIER=exec|min]"; \
	    exit 1; }
	@mkdir -p tmp
	@out='$(OUT)'; \
	 test -n "$$out" || out="tmp/$$(basename '$(firstword $(PROG))' .csp)"; \
	 ./csp -n -C -O "$$out.rom.c" $(PROG) || exit 1; \
	 $(CC) $(EXEC_FLAGS) $(ROM_TIER) -I. $(CORE_SRC) "$$out.rom.c" $(LIBS) -o "$$out" \
	    || exit 1; \
	 sed -n 's|^//   size: *|    |p' "$$out.rom.c"; \
	 echo "    $$out  <-  $(PROG)"

# The board image. Overwrites rom.c, which is the point -- and worth saying out
# loud, because rom.c and rom_host.c getting swapped is how a program ends up as
# the baseline every test then runs on top of.
rom-image: csp
	@test -n "$(PROG)" || { echo "usage: make rom-image PROG='a.csp [b.csp ...]'"; exit 1; }
	./csp -n -C -O rom.c $(PROG)
	@sed -n '1,6p' rom.c

# Chip tables: generated from chips/<vendor>/*.terms, for the TARGET only. The
# host asks the script directly -- `make chips`, `make ld CHIP=lpc2129` -- so
# nothing here compiles a table of parts it is not.
chip:
	@test -n "$(CHIP)" || { echo "usage: make chip CHIP=lpc2129"; exit 1; }
	@escript utils/gen_chips.erl $(CHIP) csp_chip.c csp_chip.h

chips:
	@escript utils/gen_chips.erl --list $(RE)

ld:
	@test -n "$(CHIP)" || { echo "usage: make ld CHIP=lpc2129"; exit 1; }
	@escript utils/gen_chips.erl --ld $(CHIP)

# Both listings take a regexp: `make chips RE=212`, `make board-list RE=dl`.
# Not `boards` -- that already means "build every board", which is the slow
# thing this is here to avoid needing.
board-list:
	@escript utils/gen_chips.erl --boards $(RE)

# Hold every board against its chip: pin functions, core clock, and whether
# anything was half-configured. `make check-boards RE=dl` for one.
check-boards:
	@escript utils/gen_chips.erl --check $(RE)

# The board's pin mux and power word: `make board BOARD=bridgezone`. Written to
# build/<board>/ because that is where a per-board build wants it, and it
# refuses to generate for a board that does not pass check-boards.
board:
	@test -n "$(BOARD)" || { echo "usage: make board BOARD=bridgezone"; exit 1; }
	@mkdir -p build/$(BOARD)
	@escript utils/gen_chips.erl --board $(BOARD) build/$(BOARD)/csp_board.h

# String table: a small C tool generates csp_strings.{c,h} from strings.tab.
strtab: strtab.c
	$(CC) -Wall -o $@ strtab.c

csp_strings.c csp_strings.h: strings.tab strtab
	./strtab strings.tab csp_strings.c csp_strings.h

# strings.tab is itself generated, from strings/*.tab.src -- one of which,
# strings/keyword.tab.src, comes out of the grammar (utils/syntax.terms), so a
# word the parser accepts and a word the string table holds cannot drift apart.
#
# Both are CHECKED IN and regenerating them is a developer action: a firmware
# build needs strtab and a C compiler, never Erlang. `make test` runs the
# staleness check instead (strings_check below).
strings:
	@escript utils/gen_strings.erl merge

# csp_tokens.h: the tok_t and dtok_t enums AND the two table bodies indexed by
# them, as CSP_TOK_TABLE / CSP_DECL_TABLE. Checked in, same policy as
# strings.tab -- regenerating is a developer action.
tables:
	@escript utils/gen_tables.erl emit

# csp_pattern_ids.h (the PAT_*/STOP_* enums) and csp_patterns.h (the capture
# structs and the pattern byte arrays). This is the one that earns its keep:
# every P_OPT/P_ALT/P_REP length is computed, and stop-set ids are allocated one
# per site instead of written by hand.
patterns:
	@escript utils/gen_patterns.erl emit

# sources that use the shared RODATA strings need the generated header first
csp_rt.o csp_repl.o csp_compile.o csp_tok.o csp_strings.o: csp_strings.h

clean:
	rm -f $(OBJS) strtab csp_strings.c csp_strings.h csp-exec csp-min

test:	csp test_repl syntax_check strings_check tables_check patterns_check sketch_check
	@chmod +x tests/run_tests.escript
	@cd $(CURDIR) && escript tests/run_tests.escript tests/unit

# utils/syntax.terms is the SOURCE the three generators read. This resolves its
# cross-references before any of them run: every capture against its struct,
# every sub-pattern and array element type, every literal against the token
# table. First, because a term file that does not hold together produces
# generated C that fails somewhere far from the mistake.
syntax_check:
	@escript utils/syntax_check.erl utils/syntax.terms

# strings.tab must be what strings/*.tab.src produce. Catches a hand edit to the
# generated file, and a grammar edit that never made it into the string table.
strings_check:
	@escript utils/gen_strings.erl check

# Same for the token tables: the checked-in files must be what syntax.terms
# produces. The enum/row mismatch itself is prevented by construction -- one
# list emits both, and a member meant to have no row has to say so -- this
# catches a hand edit to a generated file, or a terms edit never regenerated.
tables_check:
	@escript utils/gen_tables.erl check

patterns_check:
	@escript utils/gen_patterns.erl check

# The Arduino sketch folder reaches the sources through symlinks. A REGULAR file
# there shadows one and freezes it: csp_patterns.h sat as a stale copy for a
# while and the boards quietly built against it, so a header change showed up in
# the host tests and nowhere else. Cheap to check, silent to miss.
sketch_check:
	@for f in CandySpeak/csp_*.h CandySpeak/csp_*.c; do \
	    test -L "$$f" || { echo "$$f is a regular file, not a symlink"; exit 1; }; \
	done; echo "CandySpeak/: ok -- all sources are symlinks"

# REPL/persistence level: /list segment tags, what a /clear keeps, and whether a
# generated ROM image loads back into the firmware that links it. None of that is
# reachable from the unit suite, which only reads variables out of a state dump.
# Fast, so it runs as part of `make test` -- unlike test_crc_destroyer.
test_repl: csp
	@bash tests/repl.sh

# The cases that WAIT: over-long lines with no terminator, where the answer is
# a timeout rather than an output. Four of them, and they were most of the
# suite's wall clock -- so they are not in the loop you run after every edit.
test_slow: csp
	@bash tests/slow.sh

# Everything, including every board. Minutes, not seconds: arduino-cli compiles
# the whole core per target. For a release, not for a change.
test_all: test test_slow boards_all

boards_all:
	@for f in CandySpeak/Makefile.*; do \
	    b=$${f##*Makefile.}; \
	    printf '%-14s ' "$$b"; \
	    out=$$($(MAKE) -C CandySpeak -f Makefile.$$b 2>&1); \
	    if echo "$$out" | grep -q 'Sketch uses'; then \
		echo "$$out" | grep -E 'Sketch uses|Global variables' | \
		  sed -E 's/.*Sketch uses ([0-9]+) bytes \(([0-9]+)%\).*/flash \1 (\2%)/; \
		          s/.*Global variables use ([0-9]+) bytes \(([0-9]+)%\).*/ram \1 (\2%)/' | \
		  tr '\n' ' '; echo; \
	    else \
		echo "$$out" | grep -iE 'undefined reference|error:' | head -1 | cut -c1-90; \
	    fi; \
	done

test-examples: csp
	@chmod +x tests/run_tests.escript
	@cd $(CURDIR) && escript tests/run_tests.escript examples

# CRC destroyer: flip bits across a saved EEPROM image under ASan/UBSan and prove
# every corrupted load is handled gracefully (restore / reject / recover) and
# NEVER crashes. Slow (rebuilds sanitized, forks per corruption) -- NOT part of
# `make test`. 1-bit is exhaustive; multi-bit sampled. Tune with:
#   CRC_MAX1=<n> CRC_MULTI=<n> make test_crc_destroyer
test_crc_destroyer:
	@chmod +x tests/crc_destroyer.sh
	@bash tests/crc_destroyer.sh

%.o:	%.c
	$(CC) $(CFLAGS) -c -fPIC $<

.%.d:	;

-include .*.d

.PHONY: chips board-list check-boards board ld chip all clean test test-examples test_repl test_crc_destroyer syntax_check strings strings_check tables tables_check patterns patterns_check sketch_check debug ubsan san exec min rom rom-image

# Regenerate csp_boards.h from the firmware builds, so --board on the host uses
# MEASURED numbers instead of hand-fed ones. Needs both boards built first
# (make -C CandySpeak -f Makefile.mega / Makefile.mkrzero).
boards:
	@{ echo "// GENERATED by 'make boards' from the firmware ELFs -- do not edit."; \
	   echo "// system = statics - arena: the core plus every linked library, i.e."; \
	   echo "// what is taken BEFORE CandySpeak claims what is left. Re-run after"; \
	   echo "// changing which libraries a sketch links in."; \
	   echo "#ifndef __CSP_BOARDS_H__"; echo "#define __CSP_BOARDS_H__"; echo; \
	   ./board_ram.sh mega 8192 4096 avr-nm \
	     CandySpeak/build/tmp.arduino.avr.mega/CandySpeak.ino.elf; echo; \
	   ./board_ram.sh mkrzero 32768 2048 arm-none-eabi-nm \
	     CandySpeak/build/arduino.samd.mkrzero/CandySpeak.ino.elf; echo; \
	   echo "#endif"; } > csp_boards.h
	@sed -n '/^\/\* /p;/^#define/p' csp_boards.h
