// strtab.c - generate csp_strings.{c,h} from a strings.tab table.
//
// strings.tab: one entry per line, "NAME literal" -- NAME (no s_ prefix) is the
// first whitespace-delimited token, the literal is the rest of the line (may be
// empty, e.g. for the null string). Lines that are blank or start with '#' are
// ignored. Generated declarations are `rochar s_NAME[] RODATA`.
//
// usage: strtab strings.tab csp_strings.c csp_strings.h

#include <stdio.h>
#include <string.h>

int main(int argc, char** argv)
{
    FILE *in, *fc, *fh;
    char line[256];

    if (argc != 4) {
	fprintf(stderr, "usage: %s <strings.tab> <out.c> <out.h>\n", argv[0]);
	return 1;
    }
    if (!(in = fopen(argv[1], "r")) ||
	!(fc = fopen(argv[2], "w")) ||
	!(fh = fopen(argv[3], "w"))) {
	perror("strtab");
	return 1;
    }

    fprintf(fh, "// generated by strtab from strings.tab -- do not edit\n");
    fprintf(fh, "#ifndef __CSP_STRINGS_H__\n#define __CSP_STRINGS_H__\n");
    fprintf(fh, "#include \"csp.h\"\n\n");
    fprintf(fc, "// generated by strtab from strings.tab -- do not edit\n");
    fprintf(fc, "#include \"csp.h\"\n\n");

    while (fgets(line, sizeof(line), in)) {
	char name[128];
	char* p = line;
	char* q;
	int i = 0;

	q = strpbrk(line, "\r\n");   // strip line ending
	if (q) *q = '\0';
	if (line[0] == '\0' || line[0] == '#')  // blank / comment
	    continue;

	while (*p && *p != ' ' && *p != '\t')   // NAME = first token
	    name[i++] = *p++;
	name[i] = '\0';
	while (*p == ' ' || *p == '\t')          // skip to the literal
	    p++;

	// Emit the array SIZE in the extern so sizeof(s_X) (used by CSTRLEN in
	// the tables) works across translation units -- an unsized extern array
	// is an incomplete type. Size = string length + 1 for the terminator.
	fprintf(fh, "extern rochar s_%s[%d] RODATA;\n", name, (int)strlen(p) + 1);
	fprintf(fh, "#define ros_%s ((rostring_t) s_%s)\n", name, name);
	
	fprintf(fc, "rochar s_%s[] RODATA = \"", name);
	for (; *p; p++) {                        // literal, C-escaped
	    if (*p == '"' || *p == '\\')
		fputc('\\', fc);
	    fputc(*p, fc);
	}
	fprintf(fc, "\";\n");
    }

    fprintf(fh, "\n#endif\n");
    fclose(in); fclose(fc); fclose(fh);
    return 0;
}
