// generated by utils/gen_patterns.erl from utils/syntax.terms -- do not edit
//
// Capture structs and pattern byte arrays. Every byte length here was
// computed, not counted. See utils/syntax.terms for what each pattern
// means and why it is shaped the way it is.
#ifndef __CSP_PATTERNS_H__
#define __CSP_PATTERNS_H__

#define MAX_BODY_PARTS 8
#define MAX_INITS 8
#define MAX_PACK MAX_BODY_PARTS

typedef struct {
    ivalue_t res;
} res_param_t;
typedef struct {
    ivalue_t port;
    ivalue_t pin;
} port_pin_t;
typedef struct {
    value_t init;
    decl_opts_t opts;
    ivalue_t sep;
} initval_param_t;
typedef struct {
    ivalue_t num;
    ivalue_t colon;
    ivalue_t lo;
    ivalue_t hi;
    ivalue_t sep;
} pin_item_t;
typedef struct {
    tstr_t name;
} module_param_t;
typedef struct {
} end_param_t;
typedef struct {
    tstr_t name;
    res_param_t r;
    decl_opts_t opts;
    value_t init;
} variable_param_t;
typedef struct {
    tstr_t name;
    res_param_t r;
    decl_opts_t opts;
    value_t init;
    ivalue_t list;
} constant_param_t;
typedef struct {
    tstr_t name;
    port_pin_t port_pin;
    decl_opts_t opts;
} digital_param_t;
typedef struct {
    tstr_t name;
    res_param_t r;
    port_pin_t port_pin;
    decl_opts_t opts;
} analog_param_t;
typedef struct {
    tstr_t name;
    ivalue_t timeout;
    ivalue_t init;
} timer_param_t;
typedef struct {
    tstr_t name;
    res_param_t r;
    tstr_t frame;
    ivalue_t bit0;
    ivalue_t bit1;
    decl_opts_t opts;
} field_param_t;
typedef struct {
    tstr_t name;
    res_param_t r;
    decl_opts_t opts;
    ivalue_t frameid;
    uint8_t is_can;
} buffer_param_t;
typedef struct {
    tstr_t obj;
    tstr_t fld;
    tstr_t pfld;
    ivalue_t assign;
    ivalue_t has_idx;
    ivalue_t has_range;
    int idx_bits;
    int is_unpack;
    index_t src_view;
    ivalue_t idx0;
    ivalue_t idx1;
    pexpr_t idxe;
    pexpr_t rhs;
} rule_body_part_t;
typedef struct {
    pexpr_t cond;
    rule_body_part_t body[MAX_BODY_PARTS];
} rule_param_t;
typedef struct {
    tstr_t mod_name;
    tstr_t obj_name;
    rule_body_part_t inits[MAX_INITS];
} object_param_t;
typedef struct {
    pexpr_t val;
    ivalue_t bits;
} pack_field_t;
typedef struct {
    pack_field_t field[MAX_PACK];
    tstr_t buffer;
    ivalue_t op;
    pexpr_t cond;
} pack_param_t;

static const uint8_t pat_res[] = {
    P_OPT, 6,
        P_TOK, COLON,
        P_INTEGER_S, csp_offsetof(res_param_t, res), STOP_RES_RES,
        P_OPT_END,
    P_END,
};

static const uint8_t pat_port_pin[] = {
    P_CHOICE, 2,
        P_ALT, 9,
            P_INTEGER_S, csp_offsetof(port_pin_t, port), STOP_PORT_PIN_PORT,
            P_TOK, COLON,
            P_INTEGER_S, csp_offsetof(port_pin_t, pin), STOP_PORT_PIN_PIN,
            P_ALT_END,
        P_ALT, 4,
            P_INTEGER_S, csp_offsetof(port_pin_t, pin), STOP_PORT_PIN_PIN_2,
            P_ALT_END,
    P_CHOICE_END,
    P_OPT, 3,
        P_TOK, COMMA,
        P_OPT_END,
    P_END,
};

static const uint8_t pat_initval[] = {
    P_CONST_S, csp_offsetof(initval_param_t, opts), csp_offsetof(initval_param_t, init), STOP_INITVAL_INIT,
    P_CHOICE, 2,
        P_ALT, 4,
            P_TOK_W, COMMA, csp_offsetof(initval_param_t, sep),
            P_ALT_END,
        P_ALT, 4,
            P_TOK_W, RBRACE, csp_offsetof(initval_param_t, sep),
            P_ALT_END,
    P_CHOICE_END,
    P_END,
};

static const uint8_t pat_pin_item[] = {
    P_CHOICE, 2,
        P_ALT, 32,
            P_INTEGER_S, csp_offsetof(pin_item_t, num), STOP_PIN_ITEM_NUM,
            P_OPT, 18,
                P_TOK_W, COLON, csp_offsetof(pin_item_t, colon),
                P_OPT, 12,
                    P_INTEGER_S, csp_offsetof(pin_item_t, lo), STOP_PIN_ITEM_LO,
                    P_OPT, 6,
                        P_TOK, DOTDOT,
                        P_INTEGER_S, csp_offsetof(pin_item_t, hi), STOP_PIN_ITEM_HI,
                        P_OPT_END,
                    P_OPT_END,
                P_OPT_END,
            P_OPT, 6,
                P_TOK, DOTDOT,
                P_INTEGER_S, csp_offsetof(pin_item_t, hi), STOP_PIN_ITEM_HI_2,
                P_OPT_END,
            P_ALT_END,
        P_ALT, 6,
            P_TOK, DOTDOT,
            P_INTEGER_S, csp_offsetof(pin_item_t, hi), STOP_PIN_ITEM_HI_3,
            P_ALT_END,
    P_CHOICE_END,
    P_OPT, 4,
        P_TOK_W, COMMA, csp_offsetof(pin_item_t, sep),
        P_OPT_END,
    P_END,
};

static const uint8_t pat_module[] = {
    P_STR, csp_offsetof(module_param_t, name),
    P_END,
};

static const uint8_t pat_end[] = {
    P_END,
};

static const uint8_t pat_variable[] = {
    P_STR, csp_offsetof(variable_param_t, name),
    P_PAT, PAT_RES, csp_offsetof(variable_param_t, r), STOP_VARIABLE_RES_CONT,
    P_OPTS, csp_offsetof(variable_param_t, opts),
    P_OPT, 7,
        P_TOK, EQ,
        P_CONST_S, csp_offsetof(variable_param_t, opts), csp_offsetof(variable_param_t, init), STOP_VARIABLE_INIT,
        P_OPT_END,
    P_END,
};

static const uint8_t pat_constant[] = {
    P_STR, csp_offsetof(constant_param_t, name),
    P_PAT, PAT_RES, csp_offsetof(constant_param_t, r), STOP_CONSTANT_RES_CONT,
    P_OPTS, csp_offsetof(constant_param_t, opts),
    P_TOK, EQ,
    P_CHOICE, 2,
        P_ALT, 4,
            P_TOK_W, LBRACE, csp_offsetof(constant_param_t, list),
            P_ALT_END,
        P_ALT, 5,
            P_CONST_S, csp_offsetof(constant_param_t, opts), csp_offsetof(constant_param_t, init), STOP_CONSTANT_INIT,
            P_ALT_END,
    P_CHOICE_END,
    P_END,
};

static const uint8_t pat_digital[] = {
    P_STR, csp_offsetof(digital_param_t, name),
    P_OPTS, csp_offsetof(digital_param_t, opts),
    P_PAT, PAT_PORT_PIN, csp_offsetof(digital_param_t, port_pin), STOP_DIGITAL_PORT_PIN_CONT,
    P_END,
};

static const uint8_t pat_analog[] = {
    P_STR, csp_offsetof(analog_param_t, name),
    P_PAT, PAT_RES, csp_offsetof(analog_param_t, r), STOP_ANALOG_RES_CONT,
    P_OPTS, csp_offsetof(analog_param_t, opts),
    P_PAT, PAT_PORT_PIN, csp_offsetof(analog_param_t, port_pin), STOP_ANALOG_PORT_PIN_CONT,
    P_END,
};

static const uint8_t pat_timer[] = {
    P_STR, csp_offsetof(timer_param_t, name),
    P_INTEGER_S, csp_offsetof(timer_param_t, timeout), STOP_TIMER_TIMEOUT,
    P_OPT, 6,
        P_TOK, EQ,
        P_INTEGER_S, csp_offsetof(timer_param_t, init), STOP_TIMER_INIT,
        P_OPT_END,
    P_END,
};

static const uint8_t pat_field_decl[] = {
    P_STR, csp_offsetof(field_param_t, name),
    P_PAT, PAT_RES, csp_offsetof(field_param_t, r), STOP_FIELD_DECL_RES_CONT,
    P_OPTS, csp_offsetof(field_param_t, opts),
    P_STR, csp_offsetof(field_param_t, frame),
    P_TOK, LB,
    P_CHOICE, 2,
        P_ALT, 9,
            P_INTEGER_S, csp_offsetof(field_param_t, bit0), STOP_FIELD_DECL_BIT0,
            P_TOK, DOTDOT,
            P_INTEGER_S, csp_offsetof(field_param_t, bit1), STOP_FIELD_DECL_BIT1,
            P_ALT_END,
        P_ALT, 4,
            P_INTEGER_S, csp_offsetof(field_param_t, bit0), STOP_FIELD_DECL_BIT0_2,
            P_ALT_END,
    P_CHOICE_END,
    P_TOK, RB,
    P_END,
};

static const uint8_t pat_buffer[] = {
    P_STR, csp_offsetof(buffer_param_t, name),
    P_PAT, PAT_RES, csp_offsetof(buffer_param_t, r), STOP_BUFFER_RES_CONT,
    P_OPTS, csp_offsetof(buffer_param_t, opts),
    P_OPT, 6,
        P_TOK, T_CAN,
        P_INTEGER_S, csp_offsetof(buffer_param_t, frameid), STOP_BUFFER_FRAMEID,
        P_OPT_END,
    P_END,
};

static const uint8_t pat_body[] = {
    P_OPT, 63,
        P_STR, csp_offsetof(rule_body_part_t, obj),
        P_OPT, 12,
            P_TOK, DOT,
            P_STR, csp_offsetof(rule_body_part_t, fld),
            P_OPT, 5,
                P_TOK, DOT,
                P_STR, csp_offsetof(rule_body_part_t, pfld),
                P_OPT_END,
            P_OPT_END,
        P_OPT, 18,
            P_TOK_W, LB, csp_offsetof(rule_body_part_t, has_idx),
            P_INTEGER_S, csp_offsetof(rule_body_part_t, idx0), STOP_BODY_IDX0,
            P_OPT, 7,
                P_TOK_W, DOTDOT, csp_offsetof(rule_body_part_t, has_range),
                P_INTEGER_S, csp_offsetof(rule_body_part_t, idx1), STOP_BODY_IDX1,
                P_OPT_END,
            P_TOK, RB,
            P_OPT_END,
        P_OPT, 9,
            P_TOK_W, LB, csp_offsetof(rule_body_part_t, has_idx),
            P_EXPR_S, csp_offsetof(rule_body_part_t, idxe), STOP_BODY_IDXE,
            P_TOK, RB,
            P_OPT_END,
        P_CHOICE, 2,
            P_ALT, 4,
                P_TOK_W, EQ, csp_offsetof(rule_body_part_t, assign),
                P_ALT_END,
            P_ALT, 4,
                P_TOK_W, RIMP, csp_offsetof(rule_body_part_t, assign),
                P_ALT_END,
        P_CHOICE_END,
        P_OPT_END,
    P_EXPR_S, csp_offsetof(rule_body_part_t, rhs), STOP_BODY_RHS,
    P_END,
};

static const uint8_t pat_rule[] = {
    P_PAT, PAT_BODY, csp_offsetof(rule_param_t, body), STOP_RULE_BODY_CONT,
    P_REP, 10,
        P_ARRAY, csp_offsetof(rule_param_t, body[1]), sizeof(rule_body_part_t),
        P_TOK, COMMA,
        P_PAT, PAT_BODY, 0, STOP_RULE_BODY_CONT,
        P_REP_END,
    P_OPT, 6,
        P_TOK, QUEST,
        P_EXPR_S, csp_offsetof(rule_param_t, cond), STOP_RULE_COND,
        P_OPT_END,
    P_END,
};

static const uint8_t pat_object[] = {
    P_STR, csp_offsetof(object_param_t, mod_name),
    P_STR, csp_offsetof(object_param_t, obj_name),
    P_OPT, 11,
        P_REP, 8,
            P_ARRAY, csp_offsetof(object_param_t, inits), sizeof(rule_body_part_t),
            P_PAT, PAT_BODY, 0, STOP_OBJECT_BODY_CONT,
            P_REP_END,
        P_OPT_END,
    P_END,
};

static const uint8_t pat_pack_field[] = {
    P_EXPR_S, csp_offsetof(pack_field_t, val), STOP_PACK_FIELD_VAL,
    P_OPT, 6,
        P_TOK, COLON,
        P_INTEGER_S, csp_offsetof(pack_field_t, bits), STOP_PACK_FIELD_BITS,
        P_OPT_END,
    P_END,
};

static const uint8_t pat_pack[] = {
    P_STR, csp_offsetof(pack_param_t, buffer),
    P_CHOICE, 2,
        P_ALT, 4,
            P_TOK_W, LTLT, csp_offsetof(pack_param_t, op),
            P_ALT_END,
        P_ALT, 4,
            P_TOK_W, GTGT, csp_offsetof(pack_param_t, op),
            P_ALT_END,
    P_CHOICE_END,
    P_TOK, EQ,
    P_REP, 8,
        P_ARRAY, csp_offsetof(pack_param_t, field), sizeof(pack_field_t),
        P_PAT, PAT_PACK_FIELD, 0, STOP_PACK_PACK_FIELD_CONT,
        P_REP_END,
    P_OPT, 6,
        P_TOK, QUEST,
        P_EXPR_S, csp_offsetof(pack_param_t, cond), STOP_PACK_COND,
        P_OPT_END,
    P_END,
};

// Registration, in dependency order: a sub-pattern must be in
// pattern[] before collect_first follows a P_PAT into it.
#define CSP_SCAN_PATTERNS \
    scan_pattern(PAT_RES, pat_res); \
    scan_pattern(PAT_PORT_PIN, pat_port_pin); \
    scan_pattern(PAT_INITVAL, pat_initval); \
    scan_pattern(PAT_PIN_ITEM, pat_pin_item); \
    scan_pattern(PAT_MODULE, pat_module); \
    scan_pattern(PAT_END, pat_end); \
    scan_pattern(PAT_VARIABLE, pat_variable); \
    scan_pattern(PAT_CONSTANT, pat_constant); \
    scan_pattern(PAT_DIGITAL, pat_digital); \
    scan_pattern(PAT_ANALOG, pat_analog); \
    scan_pattern(PAT_TIMER, pat_timer); \
    scan_pattern(PAT_FIELD_DECL, pat_field_decl); \
    scan_pattern(PAT_BUFFER, pat_buffer); \
    scan_pattern(PAT_BODY, pat_body); \
    scan_pattern(PAT_RULE, pat_rule); \
    scan_pattern(PAT_OBJECT, pat_object); \
    scan_pattern(PAT_PACK_FIELD, pat_pack_field); \
    scan_pattern(PAT_PACK, pat_pack);

#endif
