# Simply use arduino-cli
#
FQBN=esp32:esp32:lilygo_t3s3
DEV=/dev/ttyACM0
BOARD=-DCSP_BOARD=boards/lilygo_t3s3.h
OPTS=--build-property "compiler.c.extra_flags=-Os $(BOARD)" \
     --build-property "compiler.cpp.extra_flags=-Os $(BOARD)"

compile:
	arduino-cli compile -e --fqbn $(FQBN) $(OPTS)

clean:
	arduino-cli compile --clean --fqbn $(FQBN) .

upload:
	arduino-cli upload -p $(DEV) --fqbn $(FQBN)
