# Simply use arduino-cli
#
FQBN=arduino:samd:adafruit_circuitplayground_m0
DEV=/dev/ttyACM0
OPTS=--build-property "compiler.c.extra_flags=-Os -DCSP_CPX" \
     --build-property "compiler.cpp.extra_flags=-Os -DCSP_CPX"

compile:
	arduino-cli compile -e --fqbn $(FQBN) $(OPTS)

clean:
	arduino-cli compile --clean --fqbn $(FQBN) .

upload:
	arduino-cli upload -p $(DEV) --fqbn $(FQBN)
