# Simply use arduino-cli
#
FQBN=arduino:samd:mkrnb1500
DEV=/dev/ttyACM0
BOARD=-DCSP_BOARD=boards/mkrnb1500.h
OPTS=--build-property "compiler.c.extra_flags=-Os $(BOARD)" \
     --build-property "compiler.cpp.extra_flags=-Os $(BOARD)"

compile:
	arduino-cli compile -e --fqbn $(FQBN) $(OPTS)

upload:
	arduino-cli upload -p $(DEV) --fqbn $(FQBN)
