# Simply use arduino-cli
#
FQBN=arduino:mbed_rp2040:pico
DEV=/dev/ttyACM0
BOARD=-DCSP_BOARD=boards/rp2040.h
OPTS=--build-property "compiler.c.extra_flags=-Os $(BOARD)" \
     --build-property "compiler.cpp.extra_flags=-Os $(BOARD)"

compile:
	arduino-cli compile -e --fqbn $(FQBN) $(OPTS)

clean:
	arduino-cli compile --clean --fqbn $(FQBN) .

upload:
	arduino-cli upload -p $(DEV) --fqbn $(FQBN)
