# Simply use arduino-cli
#
FQBN=arduino:samd:mkrnb1500
DEV=/dev/ttyACM0
OPTS=--build-property "compiler.c.extra_flags=-Os" \
     --build-property "compiler.cpp.extra_flags=-Os"

compile:
	arduino-cli compile -e --fqbn $(FQBN) $(OPTS)

upload:
	arduino-cli upload -p $(DEV) --fqbn $(FQBN)
