%%% @doc
%%%   CandySpeak to C, against csp_lib.h and csp_chip_io.h.
%%%
%%%   The program becomes one struct per module and a pair of them per cycle,
%%%   `in` (committed, what rules read) and `out` (what rules write) -- the
%%%   runtime's DIN and DOUT. A cycle is:
%%%
%%%     timers in -> inputs -> rules -> commit (in = out) -> outputs -> timers out
%%%
%%%   the same order as port/csp_avr.c's main loop, so a program means the same
%%%   thing translated as interpreted. Widths are C bit-fields: a store wraps to
%%%   the declared width the way the runtime's does.
%%%
%%%     candyspeak_c:file("prog.csp")            -> prog.c beside it
%%%     candyspeak_c:file("prog.csp", "out.c")
%%%
%%%   With -DCSP_LIB_MAIN the file carries main(): setup, then step forever on
%%%   csp_chip_millis -- Arduino's setup()/loop(), on csp_chip_*. Without it a
%%%   harness drives csp_lib_setup/csp_lib_step (tools/csp_lib_host.c).
%%%
%%%   NOT YET: arrays, float, buffers and fields, CAN, events, `.pin` set per
%%%   instance, elapsed(). Each is refused by name rather than
%%%   translated wrong.
%%% @end
-module(candyspeak_c).

-export([file/1, file/2, main/1]).

-define(IND, "    ").

main([In]) -> main([In, filename:rootname(In) ++ ".c"]);
main([In, Out]) ->
    case file(In, Out) of
        ok -> halt(0);
        {error, E} -> io:format(standard_error, "~s: ~p\n", [In, E]), halt(1)
    end.

file(In) ->
    file(In, filename:rootname(In) ++ ".c").

file(In, Out) ->
    case candyspeak:build(In) of
        {ok, Main} ->
            try gen(Main, In) of
                Text -> file:write_file(Out, Text)
            catch
                throw:{unsupported, What, Ln} ->
                    io:format(standard_error, "~s:~w: not translated to C: ~s\n",
                              [In, Ln, What]),
                    {error, unsupported}
            end;
        Error ->
            Error
    end.

%% ------------------------------------------------------------------
%% The program
%% ------------------------------------------------------------------

gen({{module, _, {'WORD', _, "Main"}}, Bound, Decls}, In) ->
    Mods = modules(Decls, #{}),
    States = [S || {'WORD', _, S} <- maps:get(states, Bound, [])],
    Main = {"Main", Decls},
    Order = module_order(Main, Mods),
    %% #define and #constant at the top are emitted as C #defines, so they are
    %% in scope in every module -- an imported library's constants included.
    Globals = maps:filter(fun(_, {const, _}) -> true; (_, _) -> false end,
                          symbols(Decls, Mods)),
    [header(In, States),
     [defines(Ds) || {_, Ds} <- [Main | [maps:get(M, Mods) || M <- Order]]],
     [module(M, maps:get(M, Mods), Mods, States, Globals) || M <- Order],
     module("Main", Decls, Mods, States, Globals),
     driver(Mods, Decls)].

%% Every module definition, by name -- the imported library ones included.
modules([{{module, _, {'WORD', _, Name}}, _B, Ds} | T], Acc) ->
    modules(T, modules(Ds, Acc#{Name => Ds}));
modules([_ | T], Acc) -> modules(T, Acc);
modules([], Acc) -> Acc.

%% Modules a module instantiates come before it: C wants the struct first.
module_order({_, Ds}, Mods) ->
    lists:reverse(order(used(Ds), Mods, [])).

order([M | T], Mods, Acc) ->
    case lists:member(M, Acc) of
        true -> order(T, Mods, Acc);
        false ->
            Ds = module_ds(M, Mods, 0),
            Acc1 = order(used(Ds), Mods, Acc),
            order(T, Mods, [M | Acc1])
    end;
order([], _Mods, Acc) -> Acc.

used(Ds) -> [M || {object, _, {'WORD', _, M}, _, _} <- Ds].

module_ds(M, Mods, Ln) ->
    case maps:find(M, Mods) of
        {ok, Ds} -> Ds;
        error -> throw({unsupported, "unknown module " ++ M, Ln})
    end.

header(In, States) ->
    ["// Generated by utils/candyspeak_c.erl. Do not edit: edit the .csp.\n",
     "//\n",
     "// Sources, the program first and then each import in the order it came in:\n",
     [["//   ", F, "\n"] || F <- sources(In)],
     "\n",
     "#include <stdint.h>\n#include <string.h>\n#include \"csp_lib.h\"\n",
     "#if defined(CSP_LIB_HOST)\n#include \"csp_lib_host.h\"\n#endif\n\n",
     "// tick() and cycle(): the time of this cycle and its number, from 1.\n",
     "static uint32_t csp_now;\nstatic uint32_t csp_cycle;\n\n",
     "enum {\n",
     [[?IND, S, " = ", integer_to_list(N), ",\n"]
      || {S, N} <- lists:zip(States, lists:seq(0, length(States) - 1))],
     "};\n\n"].

%% Absolute paths, so a .c found later can be traced to exactly the files it
%% was made from. candyspeak:parse/2 with `sources` marks where each import
%% begins; an import seen twice is read once and listed once.
sources(In) ->
    Marks = case candyspeak:parse(In, [sources]) of
                {ok, Ast} -> [P || {source, 0, P} <- Ast];
                _ -> []
            end,
    uniq([abs_path(F) || F <- [In | Marks]], []).

uniq([F | T], Acc) ->
    case lists:member(F, Acc) of
        true -> uniq(T, Acc);
        false -> uniq(T, Acc ++ [F])
    end;
uniq([], Acc) -> Acc.

abs_path(F) ->
    norm(filename:split(filename:absname(F)), []).

norm([".." | T], [_ | Acc]) -> norm(T, Acc);
norm([".." | T], []) -> norm(T, []);
norm(["." | T], Acc) -> norm(T, Acc);
norm([P | T], Acc) -> norm(T, [P | Acc]);
norm([], Acc) -> filename:join(lists:reverse(Acc)).

defines(Ds) ->
    [[case D of
          {define, _, {'WORD', _, N}, E} ->
              ["#define ", N, " (", cexpr(E, #{}), ")\n"];
          {constant, Ln, {'WORD', _, N}, scalar, _Res, _Opts, E} ->
              check_const(E, Ln),
              ["#define ", N, " (", cexpr(E, #{}), ")\n"];
          {constant, Ln, _, _, _, _, _} ->
              throw({unsupported, "#constant array", Ln});
          _ -> []
      end || D <- Ds], "\n"].

check_const({'FLT', Ln, _}, _) -> throw({unsupported, "float", Ln});
check_const(_, _) -> ok.

%% ------------------------------------------------------------------
%% A module: its struct, init, rules, and the walks for timers and pins
%% ------------------------------------------------------------------

module(Name, Ds, Mods, States, Globals) ->
    Sym = maps:merge(Globals, symbols(Ds, Mods)),
    Env = #{sym => Sym, mods => Mods, states => States, main => Name =:= "Main"},
    T = [Name, "_t"],
    ["typedef struct {\n",
     ?IND, "int32_t State;\n",
     [field(D) || D <- Ds],
     "} ", T, ";\n\n",
     init(Name, Ds, Env),
     walk(Name, "timers_in", "uint32_t now", Ds, Env),
     walk(Name, "timers_out", "uint32_t now", Ds, Env),
     wait_fn(Name, Ds),
     "#if !defined(CSP_LIB_HOST)\n",
     io_fn(Name, "config", Ds, Env),
     io_fn(Name, "input", Ds, Env),
     io_fn(Name, "output", Ds, Env),
     "#endif\n\n",
     "static void ", Name, "_run(", T, "* in, ", T, "* out)\n{\n",
     timer_starts(Ds, Env),
     body(Ds, ?IND, Env, top),
     ?IND, "// INIT lasts one cycle unless a rule said otherwise; FAILSAFE\n",
     ?IND, "// is left only by a reset.\n",
     ?IND, "if ((in->State == INIT) && (out->State == INIT))\n",
     ?IND, ?IND, "out->State = NORMAL;\n",
     ?IND, "if (in->State == FAILSAFE)\n",
     ?IND, ?IND, "out->State = FAILSAFE;\n",
     "}\n\n"].

%% name -> {Kind, Decl}
symbols(Ds, Mods) ->
    lists:foldl(
      fun(D, Acc) ->
              case D of
                  {variable, _, {'WORD', _, N}, _, _, _, _} -> Acc#{N => {var, D}};
                  {param, _, {'WORD', _, N}, _, _, _} -> Acc#{N => {var, D}};
                  {digital, _, {'WORD', _, N}, _, _, _, _} -> Acc#{N => {digital, D}};
                  {analog, _, {'WORD', _, N}, _, _, _, _} -> Acc#{N => {analog, D}};
                  {timer, _, {'WORD', _, N}, _, _} -> Acc#{N => {timer, D}};
                  {local, _, {'WORD', _, N}, _, _, _} -> Acc#{N => {local, D}};
                  {constant, _, {'WORD', _, N}, _, _, _, _} -> Acc#{N => {const, D}};
                  {define, _, {'WORD', _, N}, _} -> Acc#{N => {const, D}};
                  {object, Ln, {'WORD', _, M}, {'WORD', _, N}, _} ->
                      Acc#{N => {object, M, symbols(module_ds(M, Mods, Ln), Mods)}};
                  _ -> Acc
              end
      end, #{}, Ds).

field({variable, Ln, {'WORD', _, N}, Arr, Res, Opts, _}) ->
    scalar(Arr, Ln), [?IND, ctype(Res, Opts, Ln), " ", N, width(Res), ";\n"];
field({param, Ln, {'WORD', _, N}, Res, Opts, _}) ->
    [?IND, ctype(Res, Opts, Ln), " ", N, width(Res), ";\n"];
field({local, Ln, {'WORD', _, N}, Res, Opts, _}) ->
    [?IND, ctype(Res, Opts, Ln), " ", N, width(Res), ";\n"];
field({digital, Ln, {'WORD', _, N}, Arr, _, _, _}) ->
    scalar(Arr, Ln), [?IND, "uint32_t ", N, ":1;\n"];
field({analog, Ln, {'WORD', _, N}, Arr, Res0, Opts, _}) ->
    Res = analog_res(Res0),
    scalar(Arr, Ln), [?IND, ctype(Res, analog_opts(Opts), Ln), " ", N, width(Res), ";\n"];
field({timer, _, {'WORD', _, N}, _, _}) ->
    [?IND, "csp_timer_t ", N, ";\n"];
field({object, _, {'WORD', _, M}, {'WORD', _, N}, _}) ->
    [?IND, M, "_t ", N, ";\n"];
field({buffer, Ln, _, _, _, _}) -> throw({unsupported, "#buffer", Ln});
field({field, Ln, _, _, _, _, _}) -> throw({unsupported, "#field", Ln});
field(_) -> [].

scalar(scalar, _) -> ok;
scalar(_, Ln) -> throw({unsupported, "array", Ln}).

%% An #analog is unsigned unless it says `integer`: a converter delivers
%% counts. The runtime's csp_parse_analog has the same default.
analog_res(default) -> {'INT', 0, "10"};      % csp_parse_analog's default
analog_res(Res) -> Res.

analog_opts(Opts) ->
    case proplists:is_defined(type, Opts) of
        true -> Opts;
        false -> [{type, unsigned} | Opts]
    end.

%% A typeless declaration is signed -- except `:1`, which holds 0 and 1 rather
%% than 0 and -1, or every `Flag == 1` would be false.
ctype(Res, Opts, Ln) ->
    Dflt = case Res of {'INT', _, "1"} -> unsigned; _ -> integer end,
    case proplists:get_value(type, Opts, Dflt) of
        integer -> "int32_t";
        unsigned -> "uint32_t";
        float -> throw({unsupported, "float", Ln});
        string -> throw({unsupported, "string", Ln})
    end.

width(default) -> "";
width({'INT', _, "32"}) -> "";
width({'INT', _, W}) -> [":", W].

%% The declared values. A plain name in an initialiser is read from the struct
%% being built, which is what makes `#variable Pt = SD` follow a parameter.
init(Name, Ds, Env) ->
    ["static void ", Name, "_init(", Name, "_t* s)\n{\n",
     ?IND, "memset(s, 0, sizeof(*s));\n",
     [init1(D, Env) || D <- Ds],
     "}\n\n"].

init1({variable, _, {'WORD', _, N}, _, _, _, E}, Env) when E =/= undefined ->
    [?IND, "s->", N, " = ", iexpr(E, Env), ";\n"];
init1({param, _, {'WORD', _, N}, _, _, E}, Env) when E =/= undefined ->
    [?IND, "s->", N, " = ", iexpr(E, Env), ";\n"];
init1({local, _, {'WORD', _, N}, _, Opts, E}, Env) when E =/= undefined ->
    case is_formula(Opts) of
        true -> [];
        false -> [?IND, "s->", N, " = ", iexpr(E, Env), ";\n"]
    end;
init1({timer, _, {'WORD', _, N}, P, E}, Env) ->
    [?IND, "s->", N, ".period = ", iexpr(P, Env), ";\n",
     case E of
         undefined -> [];
         _ -> [?IND, "s->", N, ".val = ", timer_val(iexpr(E, Env)), ";\n"]
     end];
init1({object, _, {'WORD', _, M}, {'WORD', _, N}, _}, _Env) ->
    [?IND, M, "_init(&s->", N, ");\n"];
init1(_, _) -> [].

iexpr(E, Env) -> cexpr(E, Env#{rd => "s->", lrd => "s->"}).

%% `#timer T p = 1` is ALSO stored in the module's INIT, in its own body --
%% after anything the instantiating line wrote into T, so the declaration has
%% the last word, as it has in the runtime.
timer_starts(Ds, Env) ->
    [[?IND, "if (in->State == INIT) ",
      store({timer_val, ["out->", N, ".val"]}, cexpr(E, Env))]
     || {timer, _, {'WORD', _, N}, _, E} <- Ds, E =/= undefined].

%% Timers in every instance, depth first.
walk(Name, What, Arg, Ds, _Env) ->
    T = [Name, "_t"],
    ["static void ", Name, "_", What, "(", T, "* in, ", T, "* out, ", Arg, ")\n{\n",
     [case D of
          {timer, _, {'WORD', _, N}, _, _} ->
              [?IND, lib_timer(What), "(&in->", N, ", &out->", N, ", now);\n"];
          {object, _, {'WORD', _, M}, {'WORD', _, N}, _} ->
              [?IND, M, "_", What, "(&in->", N, ", &out->", N, ", now);\n"];
          _ -> []
      end || D <- Ds],
     ?IND, "(void)in; (void)out; (void)now;\n",
     "}\n\n"].

lib_timer("timers_in") -> "csp_lib_timer_in";
lib_timer("timers_out") -> "csp_lib_timer_out".

%% How long until the next timer runs out: the virtual clock jumps by this.
wait_fn(Name, Ds) ->
    ["static void ", Name, "_wait(", Name, "_t* s, uint32_t now, uint32_t* w)\n{\n",
     [case D of
          {timer, _, {'WORD', _, N}, _, _} ->
              [?IND, "if (s->", N, ".running) {\n",
               ?IND, ?IND, "uint32_t dt = now - s->", N, ".t0;\n",
               ?IND, ?IND, "uint32_t r = (dt >= s->", N, ".period) ? 0 : s->",
               N, ".period - dt;\n",
               ?IND, ?IND, "if (r < *w) *w = r;\n",
               ?IND, "}\n"];
          {object, _, {'WORD', _, M}, {'WORD', _, N}, _} ->
              [?IND, M, "_wait(&s->", N, ", now, w);\n"];
          _ -> []
      end || D <- Ds],
     ?IND, "(void)s; (void)now; (void)w;\n",
     "}\n\n"].

%% Pins. config once, input into `out` before the rules, output from the
%% committed copy after them. The host harness calls none of these: on the
%% host, as in port/csp_linux.c, a pin is what the stimulus wrote.
io_fn(Name, What, Ds, _Env) ->
    T = [Name, "_t"],
    ["static void ", Name, "_", What, "(", T, "* s)\n{\n",
     [io1(What, D) || D <- Ds],
     ?IND, "(void)s;\n",
     "}\n\n"].

io1(What, {digital, Ln, {'WORD', _, N}, _, _, Opts, Pins}) ->
    {Port, Pin} = port_pin(Pins, Ln),
    Dir = proplists:get_value(dir, Opts, in),
    Pull = case proplists:get_value(pull, Opts) of
               pullup -> "CSP_CHIP_PULLUP";
               pulldown -> "CSP_CHIP_PULLDOWN";
               _ -> "0"
           end,
    case {What, Dir} of
        {_, inout} -> throw({unsupported, "#digital inout", Ln});
        {"config", _} ->
            [?IND, "csp_chip_dcfg(", Port, ", ", Pin, ", ", cdir(Dir), ", ",
             Pull, ");\n"];
        {"input", in} ->
            [?IND, "s->", N, " = csp_chip_din(", Port, ", ", Pin, ");\n"];
        {"output", out} ->
            [?IND, "csp_chip_dout(", Port, ", ", Pin, ", s->", N, ");\n"];
        _ -> []
    end;
io1(What, {analog, Ln, {'WORD', _, N}, _, Res, Opts, Pins}) ->
    {Port, Pin} = port_pin(Pins, Ln),
    Dir = proplists:get_value(dir, Opts, in),
    Pwm = case proplists:get_bool(pwm, Opts) of true -> "1"; false -> "0" end,
    {'INT', _, R} = analog_res(Res),
    Sgn = case proplists:get_value(type, analog_opts(Opts)) of
              unsigned -> "0"; _ -> "1" end,
    case {What, Dir} of
        {_, inout} -> throw({unsupported, "#analog inout", Ln});
        {"config", _} ->
            [?IND, "csp_chip_acfg(", Port, ", ", Pin, ", ", cdir(Dir), ", ",
             Pwm, ");\n"];
        {"input", in} ->
            [?IND, "s->", N, " = csp_lib_ain(csp_chip_ain(", Port, ", ", Pin,
             "), ", R, ", ", Sgn, ");\n"];
        {"output", out} ->
            [?IND, "csp_chip_aout(", Port, ", ", Pin, ", csp_lib_aout(s->", N,
             ", ", R, ", ", Sgn, "));\n"];
        _ -> []
    end;
io1(What, {object, _, {'WORD', _, M}, {'WORD', _, N}, _}) ->
    [?IND, M, "_", What, "(&s->", N, ");\n"];
io1(_, _) -> [].

cdir(in) -> "CSP_CHIP_IN";
cdir(out) -> "CSP_CHIP_OUT".

port_pin([{pin, _, P}], _) -> {"0", cexpr(P, #{})};
port_pin([{port_pin, _, Po, {range, Ln, _, _}}], _) ->
    throw({unsupported, "pin range", Ln}), {Po, Po};
port_pin([{port_pin, _, Po, Pi}], _) -> {cexpr(Po, #{}), cexpr(Pi, #{})};
port_pin(_, Ln) -> throw({unsupported, "pin list", Ln}).

%% ------------------------------------------------------------------
%% Rules
%% ------------------------------------------------------------------

%% Where = top for the module's own level, where a loose rule in Main is gated
%% to INIT and NORMAL; inside an #in block the block is the gate.
body(Ds, Ind, Env, Where) ->
    [stmt(D, Ind, Env, Where) || D <- Ds].

stmt({rule, Ln, Assigns, Guard}, Ind, Env, Where) ->
    Gate = case {Where, maps:get(main, Env)} of
               {top, true} -> ["(in->State == INIT || in->State == NORMAL)"];
               _ -> []
           end,
    Cond = case Guard of
               undefined -> Gate;
               _ -> Gate ++ [ccond(Guard, Env)]
           end,
    Body = [assign(A, Ln, Env) || A <- Assigns],
    guarded(Cond, Body, Ind);
stmt({{in, _, States}, Ds}, Ind, Env, _Where) ->
    C = lists:join(" || ", [["in->State == ", S] || {'WORD', _, S} <- States]),
    [Ind, "if (", C, ") {\n", body(Ds, Ind ++ ?IND, Env, block), Ind, "}\n"];
stmt({{'when', _, Cond}, Ds}, Ind, Env, Where) ->
    [Ind, "if (", unwrap(ccond(Cond, Env)), ") {\n",
     body(Ds, Ind ++ ?IND, Env, Where), Ind, "}\n"];
stmt({local, _, {'WORD', _, N}, _, Opts, E}, Ind, Env, _Where)
  when E =/= undefined ->
    %% `#local Y = f` and `#local Y out = f` are formulas, evaluated where
    %% they stand; only `#local X in = d` gives a default.
    case is_formula(Opts) of
        true -> [Ind, "out->", N, " = ", cexpr(E, Env), ";\n"];
        false -> []
    end;
stmt({object, Ln, {'WORD', _, M}, {'WORD', _, N}, Args}, Ind, Env, _Where) ->
    object(M, N, Args, Ln, Ind, Env);
stmt({patch, Ln, _}, _, _, _) -> throw({unsupported, "> patch", Ln});
%% Rules are numbered by the runtime in instruction order; until the
%% translation numbers them the same way, a program that names one is refused.
stmt({disable, Ln, _}, _, _, _) -> throw({unsupported, "#disable", Ln});
stmt({enable, Ln, _}, _, _, _) -> throw({unsupported, "#enable", Ln});
stmt(_, _, _, _) -> [].

guarded([], Body, Ind) -> [[Ind, B] || B <- Body];
guarded([C], Body, Ind) -> guarded1(unwrap(C), Body, Ind);
guarded(Cs, Body, Ind) -> guarded1(lists:join(" && ", Cs), Body, Ind).

%% The outer parentheses of a lone condition, which `if (...)` supplies.
unwrap(C) ->
    case lists:flatten(C) of
        [$( | T] = F ->
            case balanced_outer(T, 1) of
                true -> lists:droplast(T);
                false -> F
            end;
        F -> F
    end.

%% True if the parenthesis opened at the start closes at the very end.
balanced_outer([$)], 1) -> true;
balanced_outer([$( | T], N) -> balanced_outer(T, N + 1);
balanced_outer([$) | _], 1) -> false;
balanced_outer([$) | T], N) -> balanced_outer(T, N - 1);
balanced_outer([_ | T], N) -> balanced_outer(T, N);
balanced_outer([], _) -> false.

guarded1(C, Body, Ind) ->
    [Ind, "if (", C, ") {\n",
     [[Ind, ?IND, B] || B <- Body], Ind, "}\n"].

assign({Op, _, {field, Ln, Lhs}, Rhs}, _, Env) when Op =:= '='; Op =:= '<-' ->
    store(lhs(Lhs, Ln, Env), cexpr(Rhs, Env));
assign({call, _, {'WORD', _, P}, Args}, _, Env)
  when P =:= "println"; P =:= "print" ->
    ["{ ", [print_arg(A, Env) || A <- Args],
     case P of "println" -> "csp_lib_nl(); "; _ -> "" end, "}\n"];
assign(Other, Ln, _) ->
    throw({unsupported, io_lib:format("statement ~p", [element(1, Other)]), Ln}).

print_arg({'STR', _, S}, _) -> ["csp_lib_puts(", cstring(S), "); "];
print_arg(E, Env) ->
    case is_unsigned(E, Env) of
        true -> ["csp_lib_putu(", cexpr(E, Env), "); "];
        false -> ["csp_lib_puti(", cexpr(E, Env), "); "]
    end.

cstring(S) -> io_lib:format("~p", [S]).

%% Where a store goes: a path, or {timer_val, Path} for the one-bit `val` of a
%% timer, which keeps bit 0 the way the runtime's part does.
lhs({'WORD', _, N}, Ln, Env) ->
    W = wr(Env),
    case sym(N, Env) of
        {timer, _} -> {timer_val, [W, N, ".val"]};
        {const, _} -> throw({unsupported, "store to a constant", Ln});
        undefined when N =:= "State" -> [W, "State"];
        undefined -> throw({unsupported, "unknown name " ++ N, Ln});
        _ -> [W, N]
    end;
lhs({part, _, {'WORD', _, T}, {'WORD', _, P}}, Ln, Env) ->
    case sym(T, Env) of
        {timer, _} -> [wr(Env), T, ".", timer_part(P, Ln)];
        _ -> throw({unsupported, "part ." ++ P, Ln})
    end;
lhs({fld, _, {'WORD', _, O}, {'WORD', _, N}}, Ln, Env) ->
    case sym(O, Env) of
        {object, _, MSym} ->
            case maps:get(N, MSym, undefined) of
                {timer, _} -> {timer_val, [wr(Env), O, ".", N, ".val"]};
                _ -> [wr(Env), O, ".", N]
            end;
        _ -> throw({unsupported, O ++ "." ++ N, Ln})
    end;
lhs(_, Ln, _) -> throw({unsupported, "left-hand side", Ln}).

store({timer_val, Path}, Rhs) -> [Path, " = ", timer_val(Rhs), ";\n"];
store(Path, Rhs) -> [Path, " = ", Rhs, ";\n"].

timer_val(E) ->
    case string:to_integer(lists:flatten(E)) of
        {I, []} -> integer_to_list(I band 1);
        _ -> ["(uint8_t)((", E, ") & 1)"]
    end.

is_formula(Opts) ->
    not lists:member(proplists:get_value(dir, Opts), [in, inout]).

wr(Env) -> maps:get(wr, Env, "out->").

timer_part("period", _) -> "period";
timer_part("fired", _) -> "fired";
timer_part("running", _) -> "running";
timer_part(P, Ln) -> throw({unsupported, "timer part ." ++ P, Ln}).

%% An instance: its bindings, its one-shot INIT values, then its body.
%%
%% A #local in is BOUND -- written every cycle before the call, `=` or `<-'
%% alike -- and one left unbound takes its default the same way. Any other
%% field given with `=` is set once, in the instance's own INIT; with `<-` it
%% follows the expression each cycle.
object(M, N, Args, Ln, Ind, Env) ->
    {object, M, MSym} = sym(N, Env),
    Bound = [F || {_, _, {field, _, {'WORD', _, F}}, _} <- Args],
    Binds =
        [case maps:get(F, MSym, undefined) of
             {local, {local, _, _, _, Opts, _}} ->
                 case lists:member(proplists:get_value(dir, Opts), [in, inout]) of
                     true ->
                         [Ind, member(N, F, MSym, Env, E)];
                     false -> throw({unsupported, "binding a #local out", Ln})
                 end;
             _ when Op =:= '<-' ->
                 [Ind, member(N, F, MSym, Env, E)];
             _ ->
                 [Ind, "if (in->", N, ".State == INIT) ",
                  member(N, F, MSym, Env, E)]
         end || {Op, _, {field, _, {'WORD', _, F}}, E} <- Args],
    Defaults =
        [case E of
             undefined ->
                 throw({unsupported, F ++ " is a #local in with no default", Ln});
             _ ->
                 [Ind, "out->", N, ".", F, " = ",
                  cexpr(E, Env#{sym => MSym, rd => ["in->", N, "."],
                                lrd => ["out->", N, "."]}), ";\n"]
         end
         || {F, {local, {local, _, _, _, Opts, E}}} <- maps:to_list(MSym),
            proplists:get_value(dir, Opts) =:= in,
            not lists:member(F, Bound)],
    [Binds, Defaults, Ind, M, "_run(&in->", N, ", &out->", N, ");\n"].

member(N, F, MSym, Env, E) ->
    Path = ["out->", N, ".", F],
    case maps:get(F, MSym, undefined) of
        {timer, _} -> store({timer_val, [Path, ".val"]}, cexpr(E, Env));
        _ -> store(Path, cexpr(E, Env))
    end.

%% ------------------------------------------------------------------
%% Expressions. Every operand is widened to 32 bits first, because int is 16
%% on an AVR and the runtime computes in 32.
%% ------------------------------------------------------------------

ccond(E, Env) -> cbool(E, Env).

%% An expression where only zero or nonzero matters: a guard, an #when, an
%% operand of && and ||. No CSP_LIB_BOOL, since TRUE is -1 and any nonzero is
%% as good to an `if`; and no widening cast on a lone name, since nothing is
%% computed with it.
cbool({Op, _, _, _} = E, Env) when Op =:= '&&'; Op =:= '||' ->
    ["(", lists:join([" ", atom_to_list(Op), " "],
                     [cbool(X, Env) || X <- chain(Op, E)]), ")"];
cbool({'!', _, A}, Env) -> ["!", bparen(A, Env)];
cbool({Op, _, L, R}, Env)
  when Op =:= '<'; Op =:= '<='; Op =:= '>'; Op =:= '>=';
       Op =:= '=='; Op =:= '!=' ->
    ["(", cexpr(L, Env), " ", atom_to_list(Op), " ", cexpr(R, Env), ")"];
cbool({field, Ln, F}, Env) -> ref(F, Ln, Env#{nocast => true});
cbool({call, Ln, {'WORD', _, F}, Args}, Env)
  when F =:= "timeout"; F =:= "changed" ->
    call(F, Args, Ln, Env#{nocast => true});
cbool(E, Env) -> cexpr(E, Env).

%% a || b || c as one list, not as ((a || b) || c): the operator is
%% associative, and C reads the flat form the same way.
chain(Op, {Op, _, L, R}) -> chain(Op, L) ++ chain(Op, R);
chain(_, E) -> [E].

%% cbool, parenthesised unless it already is or needs none.
bparen({field, _, _} = E, Env) -> cbool(E, Env);
bparen({call, _, _, _} = E, Env) -> cbool(E, Env);
bparen({_, _, _, _} = E, Env) -> cbool(E, Env);
bparen(E, Env) -> ["(", cbool(E, Env), ")"].

sym(N, Env) -> maps:get(N, maps:get(sym, Env, #{}), undefined).

rd(Env) -> maps:get(rd, Env, "in->").
lrd(Env) -> maps:get(lrd, Env, "out->").

cexpr({'INT', _, I}, _) -> I;
cexpr({'FLT', Ln, _}, _) -> throw({unsupported, "float", Ln});
cexpr({'STR', Ln, _}, _) -> throw({unsupported, "string in an expression", Ln});
cexpr({field, Ln, F}, Env) -> ref(F, Ln, Env);
cexpr({call, Ln, {'WORD', _, F}, Args}, Env) -> call(F, Args, Ln, Env);
cexpr({'!', _, A}, Env) -> ["CSP_LIB_BOOL(!", bparen(A, Env), ")"];
cexpr({'~', _, A}, Env) -> ["(~", uparen(A, Env), ")"];
cexpr({'-', _, A}, Env) -> ["(-", uparen(A, Env), ")"];
cexpr({'+', _, A}, Env) -> uparen(A, Env);
cexpr({Op, _, L, R}, Env) when Op =:= '/'; Op =:= '%' ->
    F = case {Op, is_unsigned(L, Env) orelse is_unsigned(R, Env)} of
            {'/', false} -> "csp_lib_div";
            {'/', true} -> "csp_lib_divu";
            {'%', false} -> "csp_lib_rem";
            {'%', true} -> "csp_lib_remu"
        end,
    [F, "(", cexpr(L, Env), ", ", cexpr(R, Env), ")"];
%% cbool of these comes back in parentheses, which is what CSP_LIB_BOOL needs.
cexpr({Op, _, _, _} = E, Env)
  when Op =:= '&&'; Op =:= '||'; Op =:= '<'; Op =:= '<='; Op =:= '>';
       Op =:= '>='; Op =:= '=='; Op =:= '!=' ->
    ["CSP_LIB_BOOL", cbool(E, Env)];
cexpr({Op, _, _, _} = E, Env) when Op =:= '&'; Op =:= '|'; Op =:= '^' ->
    ["(", lists:join([" ", atom_to_list(Op), " "],
                     [cexpr(X, Env) || X <- chain(Op, E)]), ")"];
cexpr({Op, _, L, R}, Env)
  when Op =:= '+'; Op =:= '-'; Op =:= '*'; Op =:= '<<'; Op =:= '>>' ->
    ["(", cexpr(L, Env), " ", atom_to_list(Op), " ", cexpr(R, Env), ")"];
cexpr(E, _) ->
    throw({unsupported, io_lib:format("expression ~p", [element(1, E)]),
           element(2, E)}).

paren(E, Env) -> ["(", cexpr(E, Env), ")"].

%% The operand of a unary operator. A name, a number, a call and a binary
%% operation all come back from cexpr needing no more parentheses.
uparen({'INT', _, _} = E, Env) -> cexpr(E, Env);
uparen({field, _, _} = E, Env) -> cexpr(E, Env);
uparen({call, _, _, _} = E, Env) -> cexpr(E, Env);
uparen({_, _, _, _} = E, Env) -> cexpr(E, Env);
uparen(E, Env) -> paren(E, Env).


ref({'WORD', _, N}, Ln, Env) ->
    States = maps:get(states, Env, []),
    case sym(N, Env) of
        _ when N =:= "State" -> [rd(Env), "State"];
        undefined ->
            case lists:member(N, States) of
                true -> ["(int32_t)", N];
                false -> throw({unsupported, "unknown name " ++ N, Ln})
            end;
        {const, _} -> N;
        {timer, _} -> [tcast(Env), rd(Env), N, ".val"];
        {local, D} -> [cast(D, Env), lrd(Env), N];      % a #local is seen at once
        {object, _, _} -> throw({unsupported, "an object as a value", Ln});
        {_, D} -> [cast(D, Env), rd(Env), N]
    end;
ref({part, _, {'WORD', _, T}, {'WORD', _, P}}, Ln, Env) ->
    case sym(T, Env) of
        {timer, _} -> [tcast(Env), rd(Env), T, ".", timer_part(P, Ln)];
        _ -> throw({unsupported, "part ." ++ P, Ln})
    end;
ref({fld, _, {'WORD', _, O}, {'WORD', _, N}}, Ln, Env) ->
    case sym(O, Env) of
        {object, _, MSym} ->
            case maps:get(N, MSym, undefined) of
                {local, D} -> [cast(D, Env), lrd(Env), O, ".", N];
                {timer, _} -> [tcast(Env), rd(Env), O, ".", N, ".val"];
                {_, D} -> [cast(D, Env), rd(Env), O, ".", N];
                undefined when N =:= "State" -> [rd(Env), O, ".State"];
                undefined -> throw({unsupported, O ++ "." ++ N, Ln})
            end;
        _ -> throw({unsupported, O ++ "." ++ N, Ln})
    end;
ref({index, Ln, _, _}, _, _) -> throw({unsupported, "array index", Ln});
ref(_, Ln, _) -> throw({unsupported, "reference", Ln}).

%% Widening a member to 32 bits before it is computed with. Only a BIT-FIELD
%% needs it: one narrower than int promotes to int, which is 16 bits on an
%% AVR. A full int32_t or uint32_t member is already what it would be cast to.
cast(D, Env) ->
    case maps:get(nocast, Env, false) orelse not is_bitfield(D) of
        true -> "";
        false ->
            case is_unsigned_decl(D) of
                true -> "(uint32_t)";
                false -> "(int32_t)"
            end
    end.

is_bitfield({digital, _, _, _, _, _, _}) -> true;
is_bitfield({variable, _, _, _, Res, _, _}) -> narrow(Res);
is_bitfield({analog, _, _, _, Res, _, _}) -> narrow(analog_res(Res));
is_bitfield({param, _, _, Res, _, _}) -> narrow(Res);
is_bitfield({local, _, _, Res, _, _}) -> narrow(Res);
is_bitfield(_) -> true.

narrow(default) -> false;
narrow({'INT', _, "32"}) -> false;
narrow(_) -> true.

%% A timer's val, fired and running are uint8_t.
tcast(Env) ->
    case maps:get(nocast, Env, false) of
        true -> "";
        false -> "(int32_t)"
    end.

is_unsigned_decl({digital, _, _, _, _, _, _}) -> true;
is_unsigned_decl(D) when is_tuple(D) ->
    Opts = case D of
               {variable, _, _, _, _, O, _} -> O;
               {analog, _, _, _, _, O, _} -> analog_opts(O);
               {param, _, _, _, O, _} -> O;
               {local, _, _, _, O, _} -> O;
               _ -> []
           end,
    proplists:get_value(type, Opts) =:= unsigned;
is_unsigned_decl(_) -> false.

%% The usual arithmetic conversions, which are also the runtime's: one unsigned
%% operand makes the operation unsigned. Comparisons and logic yield a signed
%% truth value.
is_unsigned({field, _, {'WORD', _, N}}, Env) ->
    case sym(N, Env) of
        {local, D} -> is_unsigned_decl(D);
        {Kind, D} when Kind =:= var; Kind =:= digital; Kind =:= analog ->
            is_unsigned_decl(D);
        _ -> false
    end;
is_unsigned({field, _, {fld, _, {'WORD', _, O}, {'WORD', _, N}}}, Env) ->
    case sym(O, Env) of
        {object, _, MSym} ->
            case maps:get(N, MSym, undefined) of
                {_, D} -> is_unsigned_decl(D);
                _ -> false
            end;
        _ -> false
    end;
is_unsigned({Op, _, L, R}, Env)
  when Op =:= '+'; Op =:= '-'; Op =:= '*'; Op =:= '/'; Op =:= '%';
       Op =:= '&'; Op =:= '|'; Op =:= '^' ->
    is_unsigned(L, Env) orelse is_unsigned(R, Env);
is_unsigned({Op, _, L, _}, Env) when Op =:= '<<'; Op =:= '>>' ->
    is_unsigned(L, Env);
is_unsigned({'~', _, A}, Env) -> is_unsigned(A, Env);
is_unsigned(_, _) -> false.

call("timeout", [{field, Ln, {'WORD', _, T}}], _, Env) ->
    case sym(T, Env) of
        {timer, _} ->
            case maps:get(nocast, Env, false) of
                true -> [rd(Env), T, ".fired"];
                false -> ["CSP_LIB_BOOL(", rd(Env), T, ".fired)"]
            end;
        _ -> throw({unsupported, "timeout of a non-timer", Ln})
    end;
%% changed(X): a store this cycle -- the input sweep or a rule before this one
%% -- left the working copy different from the committed one. The runtime's
%% dirty bit, read off the two copies instead of kept beside them. A #local is
%% compared the same way, committed against working, though it reads working.
call("changed", [{field, Ln, F}], _, Env) ->
    W = wr(Env),
    Cmp = ["(", ref(F, Ln, Env#{lrd => rd(Env), nocast => true}), " != ",
           ref(F, Ln, Env#{rd => W, lrd => W, nocast => true}), ")"],
    case maps:get(nocast, Env, false) of
        true -> Cmp;
        false -> ["CSP_LIB_BOOL", Cmp]
    end;
call("tick", [], _, _) -> "(int32_t)csp_now";
call("cycle", [], _, _) -> "(int32_t)csp_cycle";
call("min", [A, B], _, Env) -> ["csp_lib_min(", cexpr(A, Env), ", ", cexpr(B, Env), ")"];
call("max", [A, B], _, Env) -> ["csp_lib_max(", cexpr(A, Env), ", ", cexpr(B, Env), ")"];
call("abs", [A], _, Env) -> ["csp_lib_abs(", cexpr(A, Env), ")"];
call("clip", [X, L, H], _, Env) ->
    ["csp_lib_clip(", cexpr(X, Env), ", ", cexpr(L, Env), ", ", cexpr(H, Env), ")"];
call(F, _, Ln, _) -> throw({unsupported, F ++ "()", Ln}).

%% ------------------------------------------------------------------
%% The driver: setup and one step, plus a name table for the host harness.
%% ------------------------------------------------------------------

driver(Mods, Decls) ->
    ["static Main_t csp_in, csp_out;\n\n",
     "void csp_lib_setup(void)\n{\n",
     ?IND, "Main_init(&csp_in);\n",
     ?IND, "csp_out = csp_in;\n",
     "#if !defined(CSP_LIB_HOST)\n",
     ?IND, "Main_config(&csp_in);\n",
     "#endif\n",
     "}\n\n",
     "// One cycle at time `now`. Returns 1 if a rule changed anything, and sets\n",
     "// *wait to the ms until the next timer runs out (0xFFFFFFFF: none).\n",
     "int csp_lib_step(uint32_t now, uint32_t* wait)\n{\n",
     ?IND, "int changed;\n",
     ?IND, "csp_now = now;\n",
     ?IND, "csp_cycle++;\n",
     ?IND, "// `> X = v` in the program: INIT sees the declared value, the patch\n",
     ?IND, "// is there from cycle 2 on.\n",
     ?IND, "if (csp_cycle == 2) {\n",
     patches(Decls, Mods, "csp_in.", ?IND ++ ?IND),
     ?IND, ?IND, "csp_out = csp_in;\n",
     ?IND, "}\n",
     ?IND, "Main_timers_in(&csp_in, &csp_out, now);\n",
     "#if !defined(CSP_LIB_HOST)\n",
     ?IND, "Main_input(&csp_out);\n",
     "#else\n",
     ?IND, "csp_lib_host_input();\n",
     "#endif\n",
     ?IND, "Main_run(&csp_in, &csp_out);\n",
     ?IND, "changed = memcmp(&csp_in, &csp_out, sizeof(csp_in)) != 0;\n",
     ?IND, "csp_in = csp_out;\n",
     "#if !defined(CSP_LIB_HOST)\n",
     ?IND, "Main_output(&csp_in);\n",
     "#endif\n",
     ?IND, "Main_timers_out(&csp_in, &csp_out, now);\n",
     ?IND, "*wait = 0xFFFFFFFFu;\n",
     ?IND, "Main_wait(&csp_in, now, wait);\n",
     ?IND, "return changed;\n",
     "}\n\n",
     names(Mods, Decls),
     "#if defined(CSP_LIB_MAIN)\n",
     "int main(void)\n{\n",
     ?IND, "uint32_t wait;\n",
     ?IND, "csp_chip_init();\n",
     ?IND, "csp_lib_setup();\n",
     ?IND, "for (;;)\n",
     ?IND, ?IND, "(void)csp_lib_step(csp_chip_millis(), &wait);\n",
     "}\n",
     "#endif\n"].

%% `> X = v` lines in the program file, applied once.
patches(Decls, Mods, S, Ind) ->
    Env = #{sym => symbols(Decls, Mods), mods => Mods, states => [],
            wr => S, rd => S, lrd => S},
    [[Ind, store(lhs(L, Ln, Env), cexpr(R, Env))]
     || {immediate, {'=', _, {field, Ln, L}, R}} <- Decls].

%% For the host harness: every scalar by its runtime name ("m.V" for a member),
%% read from the committed copy and written into the working one -- where a
%% stimulus lands in port/csp_linux.c.
names(Mods, Decls) ->
    Vars = leaves(Decls, Mods, ""),
    ["#if defined(CSP_LIB_HOST)\n",
     "#include \"csp_lib_host.h\"\n",
     [["static int32_t get_", id(N), "(void) { return (int32_t)csp_in.", N, "; }\n",
       "static void set_", id(N), "(int32_t v) { csp_out.", N, " = v; }\n"]
      || N <- Vars],
     "const csp_lib_name_t csp_lib_names[] = {\n",
     [[?IND, "{ \"", N, "\", get_", id(N), ", set_", id(N), " },\n"]
      || N <- Vars],
     ?IND, "{ 0, 0, 0 }\n};\n",
     "#endif\n\n"].

%% The runtime's name is also the C path: "m.V" is csp_in.m.V.
leaves(Ds, Mods, Pre) ->
    lists:flatmap(
      fun({object, _, {'WORD', _, M}, {'WORD', _, N}, _}) ->
              leaves(maps:get(M, Mods), Mods, Pre ++ N ++ ".");
         (D) ->
              case name_of(D) of
                  undefined -> [];
                  N -> [Pre ++ N]
              end
      end, [{state} | Ds]).

id(S) -> [case C of $. -> $_; _ -> C end || C <- S].

name_of({state}) -> "State";
name_of({variable, _, {'WORD', _, N}, _, _, _, _}) -> N;
name_of({param, _, {'WORD', _, N}, _, _, _}) -> N;
name_of({local, _, {'WORD', _, N}, _, _, _}) -> N;
name_of({digital, _, {'WORD', _, N}, _, _, _, _}) -> N;
name_of({analog, _, {'WORD', _, N}, _, _, _, _}) -> N;
name_of(_) -> undefined.
