#!/usr/bin/env escript
%% -*- erlang -*-
%%
%% Generate csp_tokens.h from utils/syntax.terms: the tok_t and dtok_t enums,
%% and the two table bodies indexed by them, as macros.
%%
%%     const op_entry_t tok_table[]  RODATA = { CSP_TOK_TABLE };
%%     const op_entry_t decl_table[] RODATA = { CSP_DECL_TABLE };
%%
%% ONE file, because that is the point: tok_table is indexed BY tok_t with
%% designated initializers, so a token added to the enum without a row is
%% silently an all-zeroes entry with a NULL name where every other row holds a
%% string. Emitting both from one list makes that impossible, and a member that
%% is MEANT to have no row has to say so.
%%
%% What moves here is DATA. find_op_entry, the op_table_* accessors and
%% find_decl_entry stay where they are, with their comments -- csp_tok.c is
%% still the one file both the compiler and the disassembler reach without
%% depending on each other.
%%
%% Macros rather than an included fragment because arduino-cli copies a sketch
%% folder by extension and does not know .i files.
%%
%%   escript utils/gen_tables.erl emit    write csp_tokens.h
%%   escript utils/gen_tables.erl check   verify it is up to date

-define(TERMS, "utils/syntax.terms").
-define(HDR,   "csp_tokens.h").

main(["emit"])  -> ok = file:write_file(?HDR, text()),
		   io:format("~s~n", [?HDR]),
		   halt(0);
main(["check"]) ->
    Want = iolist_to_binary(text()),
    case file:read_file(?HDR) of
	{ok, Want} -> io:format("~s: ok~n", [?HDR]), halt(0);
	_ ->
	    io:format("~s is out of date with ~s~n  run: make tables~n",
		      [?HDR, ?TERMS]),
	    halt(1)
    end;
main(_) ->
    io:format("usage: gen_tables.erl (emit | check)~n"),
    halt(2).

text() ->
    {ok, Terms} = file:consult(?TERMS),
    Toks  = [T || T <- Terms, element(1, T) =:= token],
    Decls = [D || D <- Terms, element(1, D) =:= decl],
    ["// generated by utils/gen_tables.erl from ", ?TERMS, " -- do not edit\n",
     "//\n"
     "// The scanner's tokens and the declaration keywords: each enum together\n"
     "// with the table its members index. Edit the terms, run `make tables`.\n",
     "#ifndef __CSP_TOKENS_H__\n#define __CSP_TOKENS_H__\n\n",
     enum("tok_t", Toks),
     "\n",
     enum("dtok_t", Decls),
     "\n",
     macro("CSP_TOK_TABLE", [row(T) || T <- Toks]),
     "\n",
     macro("CSP_DECL_TABLE", [drow(D) || D <- Decls]),
     "\n#endif\n"].

enum(Name, Rows) ->
    ["typedef enum {\n",
     "    ", name(hd(Rows)), " = 0,\n",
     [["    ", name(R), ",\n"] || R <- tl(Rows)],
     "} ", Name, ";\n"].

name(R) -> atom_to_list(element(2, R)).

%% A table body as one macro. Every line but the last carries a continuation, so
%% an empty row (an enum member with no table entry) has to be dropped BEFORE
%% the backslashes go on.
macro(Name, Rows) ->
    Body = [R || R <- Rows, R =/= []],
    ["#define ", Name, " \\\n",
     join([["    ", R] || R <- Body], " \\\n"),
     "\n"].

join([], _Sep)      -> [];
join([X], _Sep)     -> [X];
join([X | Xs], Sep) -> [X, Sep | join(Xs, Sep)].

%% TOK_ENT is INSTR_ENT with arity/prec/assoc fixed at -1/-1/NO, so a row that
%% is not an operator comes out in the shorter form -- which is how the
%% hand-written table read too.
row({token, _E}) ->
    [];
row({token, E, _Sp, Sym, Code, -1, -1, no}) ->
    io_lib:format("TOK_ENT(~s,~s,s_~s),", [E, Code, Sym]);
row({token, E, _Sp, Sym, Code, A, P, As}) ->
    io_lib:format("INSTR_ENT(~s,~s,s_~s,~p,~p,~s),", [E, Code, Sym, A, P, assoc(As)]).

assoc(left)  -> "LEFT";
assoc(right) -> "RIGHT";
assoc(no)    -> "NO".

drow({decl, _D}) ->
    [];
drow({decl, D, _Sp, Sym, Code, _Pat}) ->
    io_lib:format("DECL_ENT(~s,~s,s_~s),", [D, Code, Sym]).
