#!/usr/bin/env escript
%% -*- erlang -*-
%%
%% Two back ends for utils/words.terms.
%%
%%   gen/csp_words.h     ordinary C, one function per word
%%   gen/csp_words_bc.h  the same words as micro-csp bytecode, plus the offset
%%                       each one starts at
%%
%% The point is that they come from ONE description, so a board can link
%% whichever suits its flash without the word being written twice. The test
%% runs both against the same inputs and compares; that is the only thing that
%% makes "one source, two back ends" a fact rather than an intention.
%%
%% WHAT THE BYTECODE BACK END ACTUALLY DOES that the C one does not: stack
%% scheduling. An expression tree becomes postfix, locals get slots instead of
%% TOR/RAT juggling, and a short-circuit becomes a jump. None of that is the
%% business of whoever writes the word down.
%%
%%   escript utils/gen_words.erl (emit | check)

-mode(compile).

-define(TERMS, "utils/words.terms").
-define(CH,    "gen/csp_words.h").
-define(BCH,   "gen/csp_words_bc.h").

%% Opcodes -- must track mc_op_t in include/csp_mcsp.h.
%% Opcodes as NAMES, not numbers. The array is C source, so it can hold C
%% identifiers -- which means this generator never has to know an opcode's
%% value, and adding one in the middle of mc_op_t cannot silently renumber a
%% generated word. One list element is still exactly one byte, so the branch
%% arithmetic below is unaffected.
-define(BYE,'MC_BYE'). -define(EXIT,'MC_EXIT'). -define(LIT8,'MC_LIT8'). -define(LIT16,'MC_LIT16').
-define(DROP,'MC_DROP'). -define(DUP,'MC_DUP'). -define(ADD,'MC_ADD').
-define(SUB,'MC_SUB'). -define(AND,'MC_AND'). -define(OR,'MC_OR').
-define(EQ,'MC_EQ'). -define(NE,'MC_NE'). -define(LT,'MC_LT').
-define(JMP,'MC_JMP'). -define(JZ,'MC_JZ'). -define(DECL,'MC_DECL').
-define(ND,'MC_ND'). -define(ZEQ,'MC_ZEQ'). -define(NATIVE,'MC_NATIVE'). -define(NATIVEN,'MC_NATIVEN'). -define(CALL,'MC_CALL').
-define(LGET,'MC_LGET'). -define(LSET,'MC_LSET').

main(["emit"]) ->
    [ok = file:write_file(F, T) || {F, T} <- outputs()],
    io:format("~s ~s~n", [?CH, ?BCH]),
    halt(0);
main(["check"]) -> check(outputs());
main(_) -> io:format("usage: gen_words.erl (emit | check)~n"), halt(2).

check([]) -> io:format("~s ~s: ok~n", [?CH, ?BCH]), halt(0);
check([{F, T} | R]) ->
    Want = iolist_to_binary(T),
    case file:read_file(F) of
	{ok, Want} -> check(R);
	_ -> io:format("~s is out of date with ~s~n  run: make words~n", [F, ?TERMS]),
	     halt(1)
    end.

outputs() ->
    {ok, Terms} = file:consult(?TERMS),
    Words = [W || W = {word, _, _, _, _} <- Terms],
    Nats  = [N || N = {native, _, _, _} <- Terms],
    %% Both back ends need to know which names are words: the C one to spell
    %% the csp_ prefix a word's definition gets, the bytecode one to choose
    %% CALL over NATIVE.
    put(words, sets:from_list([element(2, W) || W <- Words])),
    [{?CH, cfile(Words)}, {?BCH, bcfile(Words, Nats)}].

%% A native is an EXISTING C function, reached from bytecode through a wrapper.
%% The wrapper is not optional: csp_print_uint is void f(csp_rt_t*, uint16_t),
%% which is not the type mc_leaf_t is, and casting between function types is
%% undefined even where the ABI happens to line up. Ten bytes each, written by
%% the generator so it is no hand work -- but it is not no bytes either.
nat_kind({native, _, 0, _}) -> leaf;
nat_kind({native, _, 1, _}) -> leaf;
nat_kind({native, _, _, _}) -> leafn.

nat_index(Nats) ->
    L = [N || N <- Nats, nat_kind(N) =:= leaf],
    S = [N || N <- Nats, nat_kind(N) =:= leafn],
    maps:from_list(
      [{element(2, N), {leaf, I}} || {N, I} <- lists:zip(L, lists:seq(0, length(L)-1))] ++
      [{element(2, N), {leafn, I}} || {N, I} <- lists:zip(S, lists:seq(0, length(S)-1))]).

banner() ->
    ["// generated by utils/gen_words.erl from utils/words.terms -- do not edit\n\n"].

%% ------------------------------------------------------------------ C back end

cfile(Words) ->
    [banner(),
     "#ifndef __CSP_WORDS_H__\n#define __CSP_WORDS_H__\n\n",
     [cword(W) || W <- Words],
     "#endif\n"].

%% Every local is DECLARED at the top and ASSIGNED where it stands. The tree is
%% built with -Wdeclaration-after-statement, so a declaration in the middle of a
%% block does not compile -- and hoisting is what the surrounding code does by
%% hand anyway.
cword({word, Name, Args, CT, Body}) ->
    Locals = clocals(Body),
    [io_lib:format("~s csp_~s(csp_rt_t* st~s)\n{\n",
		   [atom_to_list(CT), atom_to_list(Name),
		    [io_lib:format(", index_t ~s", [A]) || A <- Args]]),
     [io_lib:format("\tindex_t ~s;\n", [L]) || L <- Locals],
     case uses_st(Body) of true -> ""; false -> "\t(void)st;\n" end,
     case Locals of [] -> ""; _ -> "\n" end,
     [cstmt(S, "\t") || S <- Body],
     "}\n\n"].

clocals(Body) -> lists:usort(lists:flatten([cl(S) || S <- Body])).
cl({local, N, _})     -> [N];
cl({'if', _, T})      -> [cl(S) || S <- T];
cl({while, _, B})     -> [cl(S) || S <- B];
cl({switch, _, Cs, D}) -> [[[cl(S) || S <- B] || {_, B} <- Cs], [cl(S) || S <- D]];
cl({'if', _, T, F})   -> [[cl(S) || S <- T], [cl(S) || S <- F]];
cl(_)                 -> [].

%% A word that never reads a declaration, the count or a native does not touch
%% st, and gcc says so. Cheaper to answer here than to cast the warning away.
uses_st(X) when is_tuple(X) ->
    case element(1, X) of
	decl -> true;
	nd   -> true;
	call -> true;
	_    -> lists:any(fun uses_st/1, tuple_to_list(X))
    end;
uses_st(L) when is_list(L) -> lists:any(fun uses_st/1, L);
uses_st(_) -> false.

cstmt({local, N, E}, I) -> [I, atom_to_list(N), " = ", cexp(E), ";\n"];
cstmt({set, N, E}, I)   -> [I, atom_to_list(N), " = ", cexp(E), ";\n"];
cstmt({return, E}, I)   -> [I, "return ", cexp(E), ";\n"];
cstmt({do, E}, I)       -> [I, cexp(E), ";\n"];
cstmt({'if', C, T}, I)  -> [I, "if (", cexp(C), ") {\n", [cstmt(S, I ++ "\t") || S <- T], I, "}\n"];
cstmt({while, C, B}, I) ->
    [I, "while (", cexp(C), ") {\n", [cstmt(S, I ++ "\t") || S <- B], I, "}\n"];
%% A real C switch, not an if-chain: it is what the surrounding code writes and
%% what gcc turns into a jump table. The bytecode back end cannot do that -- it
%% emits the chain -- and the cross-check in tests/words.c is what says the two
%% still agree.
cstmt({switch, E, Cases, Default}, I) ->
    [I, "switch (", cexp(E), ") {\n",
     [[I, "case ", cexp({const, K}), ":\n",
       [cstmt(S, I ++ "\t") || S <- B], I, "\tbreak;\n"] || {K, B} <- Cases],
     case Default of
	 [] -> "";
	 _  -> [I, "default:\n", [cstmt(S, I ++ "\t") || S <- Default],
		I, "\tbreak;\n"]
     end,
     I, "}\n"];
cstmt({'if', C, T, F}, I) ->
    [I, "if (", cexp(C), ") {\n", [cstmt(S, I ++ "\t") || S <- T],
     I, "} else {\n", [cstmt(S, I ++ "\t") || S <- F], I, "}\n"].

cexp({const, N}) when is_integer(N) -> integer_to_list(N);
cexp({const, N})                    -> atom_to_list(N);
cexp({var, N})                      -> atom_to_list(N);
cexp({nd})                          -> "st->ps.nd";
cexp({index, E})                    -> ["INDEX(", cexp(E), ")"];
cexp({decl, E, F})                  -> ["decl(st, ", cexp(E), ", ", atom_to_list(F), ")"];
cexp({op, Op, A, B})                -> ["(", cexp(A), " ", cop(Op), " ", cexp(B), ")"];
cexp({andthen, A, B})               -> ["(", cexp(A), " && ", cexp(B), ")"];
cexp({orthen, A, B})                -> ["(", cexp(A), " || ", cexp(B), ")"];
cexp({call, F, As}) ->
    N = case sets:is_element(F, get(words)) of
	    true  -> "csp_" ++ atom_to_list(F);
	    false -> atom_to_list(F)
	end,
    [N, "(st", [[", ", cexp(A)] || A <- As], ")"].

cop(eq) -> "=="; cop(ne) -> "!="; cop(lt) -> "<";
cop(add) -> "+"; cop(sub) -> "-"; cop(and_) -> "&"; cop(or_) -> "|".

%% ----------------------------------------------------------- bytecode back end

wrappers(Nats) ->
    L = [F || N = {native, F, _, _} <- Nats, nat_kind(N) =:= leaf],
    S = [F || N = {native, F, _, _} <- Nats, nat_kind(N) =:= leafn],
    [[wrapper(N) || N <- Nats],
     "\n", table("csp_word_leaves", "mc_leaf_t", "lw_", L),
     table("csp_word_leavesn", "mc_leafn_t", "ln_", S)].

%% A zero-length array is a GNU extension, not ISO C, and this header is
%% included by every port. An empty table is simply not emitted.
table(Name, Ty, _Pre, []) ->
    io_lib:format("// no ~s\n#define ~s     ((const ~s*)0)\n"
		  "#define ~s_N  0\n\n", [Name, Name, Ty, Name]);
table(Name, Ty, Pre, Fs) ->
    [io_lib:format("static const ~s ~s[] = {\n", [Ty, Name]),
     [io_lib:format("    ~s~s,\n", [Pre, F]) || F <- Fs],
     "};\n",
     io_lib:format("#define ~s_N  ~p\n\n", [Name, length(Fs)])].

wrapper({native, F, 0, Ret}) ->
    [io_lib:format("static mc_cell_t lw_~s(void* c_, mc_cell_t t_)\n{\n", [F]),
     ret_call(Ret, F, ["(csp_rt_t*)c_"]), "}\n"];
wrapper({native, F, 1, Ret}) ->
    [io_lib:format("static mc_cell_t lw_~s(void* c_, mc_cell_t t_)\n{\n", [F]),
     ret_call(Ret, F, ["(csp_rt_t*)c_", "t_"]), "}\n"];
wrapper({native, F, N, Ret}) ->
    %% sp[0] is the top, so the LAST argument is nearest -- sp[N-1] is the
    %% first. The wrapper leaves one cell where N were, and returns where the
    %% stack should stand.
    Args = ["(csp_rt_t*)c_" |
	    [io_lib:format("sp_[~p]", [N - I]) || I <- lists:seq(1, N)]],
    [io_lib:format("static mc_cell_t* ln_~s(void* c_, mc_cell_t* sp_)\n{\n", [F]),
     case Ret of
	 void -> [io_lib:format("    ~s(~s);\n", [F, string:join(Args, ", ")]),
		  io_lib:format("    sp_ += ~p;\n    sp_[0] = 0;\n", [N - 1])];
	 _    -> [io_lib:format("    mc_cell_t v_ = (mc_cell_t)~s(~s);\n",
				[F, string:join(Args, ", ")]),
		  io_lib:format("    sp_ += ~p;\n    sp_[0] = v_;\n", [N - 1])]
     end,
     "    return sp_;\n}\n"].

ret_call(void, F, Args) ->
    [io_lib:format("    ~s(~s);\n    return t_;\n", [F, string:join(Args, ", ")])];
ret_call(_, F, Args) ->
    [io_lib:format("    return (mc_cell_t)~s(~s);\n", [F, string:join(Args, ", ")])].

bcfile(Words, Nats) ->
    NI = nat_index(Nats),
    %% The NAMES have to be known before the layout pass, because that is what
    %% decides word-versus-native at each call site. The offsets in this seed
    %% are wrong and unused: only membership is asked during pass one, and the
    %% real map replaces it before anything is rendered.
    put(offs, maps:from_list([{element(2, W), 0} || W <- Words])),
    %% Pass one lays every word out to learn the offsets and frame sizes; the
    %% placeholders a forward call left behind are resolved when the bytes are
    %% rendered. Lengths never change between the passes -- a call is four bytes
    %% either way -- so one layout pass is enough.
    {Code, Offs, Frames} =
	lists:foldl(fun(W, {Acc, O, Fr}) ->
			    {B, N} = bword(W, NI),
			    {Acc ++ B, O ++ [{element(2, W), length(Acc)}],
			     Fr ++ [{element(2, W), N}]}
		    end, {[], [], []}, Words),
    OffMap = maps:from_list(Offs),
    FrMap = maps:from_list(Frames),
    put(offs, OffMap), put(frames, FrMap),
    [banner(),
     "#ifndef __CSP_WORDS_BC_H__\n#define __CSP_WORDS_BC_H__\n\n",
     "// The same words as bytecode. Locals are SLOTS, not stack juggling: the\n"
     "// generator assigns them, so nothing here has to hold a variable with\n"
     "// TOR/RAT the way hand-encoding does.\n",
     [io_lib:format("#define CSP_W_~s_ENTRY ~p\n", [string:uppercase(atom_to_list(N)), O])
      || {N, O} <- Offs],
     io_lib:format("#define CSP_WORDS_BC_LEN ~p\n\n", [length(Code)]),
     wrappers(Nats),
     [io_lib:format("#define CSP_W_~s_FRAME ~p\n",
		    [string:uppercase(atom_to_list(N)), F]) || {N, F} <- Frames],
     "\n", asserts(Code), "\n",
     "static const uint8_t csp_words_bc[] = {\n",
     wrap([render(B) || B <- Code]),
     "};\n\n#endif\n"].

%% A named constant could exceed a byte, and MC_LIT8 would take the low half
%% without a word. The assert says so at compile time instead.
asserts(Code) ->
    [io_lib:format("CSP_STATIC_ASSERT((~s) <= 255,\n\t\t  \"~s does not fit a"
		   " micro-csp LIT8 operand\");\n", [A, A])
     || {cconst, A} <- lists:usort([C || C = {cconst, _} <- Code])].

render(N) when is_integer(N)  -> integer_to_list(N);
render({cconst, A})           -> atom_to_list(A);
render({field, F})            -> "MFA_" ++ string:uppercase(atom_to_list(F));
render({wlo, F})  -> integer_to_list(maps:get(F, get(offs)) band 16#FF);
render({whi, F})  -> integer_to_list((maps:get(F, get(offs)) bsr 8) band 16#FF);
render({frame, F}) -> integer_to_list(maps:get(F, get(frames)));
render({leaf, F}) ->
    %% Not built yet, and it must not LOOK built. A call needs two things this
    %% generator does not have: a leaf table to index (with a wrapper per
    %% callee, since an existing f(csp_rt_t*, uint16_t) is not the same type as
    %% mc_leaf_t and casting between function types is undefined), and word ->
    %% word calls resolved to offsets in the one shared area. Until both exist
    %% this stops at generation time rather than emitting something plausible.
    io:format("{call, ~s, ...} is not implemented: micro-csp has no leaf table"
	      " yet.~n  See doc/AVR_CODE_SIZE.md.~n", [F]),
    halt(1);
render(A) when is_atom(A)     -> atom_to_list(A).

wrap(Items) -> wrap(Items, 8, []).
wrap([], _, Acc) -> lists:reverse(Acc);
wrap(L, N, Acc) ->
    {H, T} = lists:split(min(N, length(L)), L),
    wrap(T, N, [["    ", string:join(H, ", "), ",\n"] | Acc]).

%% Arguments become locals 0..n-1; declared locals follow. One flat frame.
bword({word, Name, Args, _CT, Body}, NI) ->
    put(ni, NI), put(self, Name),
    Env0 = maps:from_list(lists:zip(Args, lists:seq(0, length(Args) - 1))),
    %% PROLOGUE: arguments arrive on the data stack -- the caller pushed them
    %% left to right, so the last one is on top -- and the word moves them into
    %% its own frame before anything else. Without this a called word reads
    %% local 0 of a frame nobody wrote.
    Pro = lists:append([[?LSET, K] || K <- lists:reverse(lists:seq(0, length(Args) - 1))]),
    {Code, Env} = lists:foldl(fun(S, {C, E}) ->
				      {C2, E2} = bstmt(S, E),
				      {C ++ C2, E2}
			      end, {[], Env0}, Body),
    {Pro ++ Code, maps:size(Env)}.

bstmt({local, N, E}, Env) ->
    K = maps:size(Env),
    Env2 = maps:put(N, K, Env),
    {bexp(E, Env) ++ [?LSET, K], Env2};
%% set is local without the declaration: the name is already in the frame, so
%% this only assigns. In C both emit the same line -- the difference is that
%% `local` is what puts the name at the top of the function.
bstmt({set, N, E}, Env) -> {bexp(E, Env) ++ [?LSET, maps:get(N, Env)], Env};
%% EXIT, not BYE: a word that halted the machine could not be called from
%% another word, which is what made leaf_mark return nothing at all. The
%% OUTERMOST exit -- an empty return stack -- is what ends a run.
bstmt({return, E}, Env) -> {bexp(E, Env) ++ [?EXIT], Env};
bstmt({do, E}, Env)     -> {bexp(E, Env) ++ [?DROP], Env};
bstmt({'if', C, T}, Env) ->
    {Tc, Env2} = bseq(T, Env),
    {bexp(C, Env) ++ [?JZ, rel(length(Tc))] ++ Tc, Env2};
bstmt({'if', C, T, F}, Env) ->
    {Tc, E1} = bseq(T, Env),
    {Fc, E2} = bseq(F, E1),
    {bexp(C, Env) ++ [?JZ, rel(length(Tc) + 2)] ++ Tc ++
	 [?JMP, rel(length(Fc))] ++ Fc, E2};
%% while: the condition is re-entered from the bottom, so the back jump spans
%% the whole loop. rel/1 refuses anything outside rel8 rather than wrapping --
%% a branch that silently lands somewhere else is the worst thing a code
%% generator can emit.
bstmt({while, C, B}, Env) ->
    {Bc, Env2} = bseq(B, Env),
    Cc = bexp(C, Env),
    Back = -(length(Cc) + 2 + length(Bc) + 2),
    {Cc ++ [?JZ, rel(length(Bc) + 2)] ++ Bc ++ [?JMP, rel(Back)], Env2};
%% switch: the subject is evaluated ONCE into a slot, then a chain of compares.
%% A jump table is what the C back end gets from gcc and this does not -- for
%% cold code that is the right side of the trade, and it keeps the bytecode
%% free of a second branch form.
bstmt({switch, E, Cases, Default}, Env) ->
    Tmp = maps:size(Env),
    Env1 = maps:put('$switch', Tmp, Env),
    {Arms, Env2} = lists:mapfoldl(fun({K, B}, Ev) ->
					  {Bc, Ev2} = bseq(B, Ev),
					  {{K, Bc}, Ev2}
				  end, Env1, Cases),
    {Dc, Env3} = bseq(Default, Env2),
    %% Every arm jumps to the end, so its trailing JMP has to know how much
    %% comes after it -- built back to front for exactly that reason.
    {Body, _} = lists:foldr(
		  fun({K, Bc}, {Acc, After}) ->
			  Test = [?LGET, Tmp, ?LIT8, {cconst, K}, ?EQ],
			  Arm = Test ++ [?JZ, rel(length(Bc) + 2)] ++ Bc
			      ++ [?JMP, rel(After)],
			  {Arm ++ Acc, After + length(Arm)}
		  end, {Dc, length(Dc)}, Arms),
    {bexp(E, Env) ++ [?LSET, Tmp] ++ Body, Env3}.

bseq(Stmts, Env) ->
    lists:foldl(fun(S, {C, E}) -> {C2, E2} = bstmt(S, E), {C ++ C2, E2} end,
		{[], Env}, Stmts).

rel(N) when N >= -128, N =< 127 -> N band 16#FF;
rel(N) -> io:format("branch out of rel8 range: ~p~n", [N]), halt(1).

bexp({const, N}, _) when is_integer(N), N =< 255 -> [?LIT8, N];
bexp({const, N}, _) when is_integer(N) -> [?LIT16, N band 255, (N bsr 8) band 255];
bexp({const, A}, _) -> [?LIT8, {cconst, A}];
bexp({var, N}, Env) -> [?LGET, maps:get(N, Env)];
bexp({nd}, _) -> [?ND];
%% INDEX() masks the object bits off a packed index. It is a macro in C and an
%% AND here -- and leaving it out of the word is not a shortcut, it is a
%% different function.
bexp({index, E}, Env) -> bexp(E, Env) ++ [?LIT16, {cconst, 'INDEX_MASK_LO'},
					  {cconst, 'INDEX_MASK_HI'}, ?AND];
bexp({decl, E, F}, Env) -> bexp(E, Env) ++ [?DECL, {field, F}];
bexp({op, Op, A, B}, Env) -> bexp(A, Env) ++ bexp(B, Env) ++ [bop(Op)];
%% Short-circuit: if the left is false the result is already on the stack as 0
%% and the right is skipped. That is the whole reason andthen is its own node
%% and not {op, and_, ...} -- the C back end needs && and this needs a jump.
bexp({andthen, A, B}, Env) ->
    Bc = bexp(B, Env),
    %% Past the JZ operand lie DROP (one byte) and the right side, so the
    %% offset is len(Bc) + 1. Writing +2 there sent the branch one byte past
    %% the end of the word, which the cross-check caught as MC_E_BOUNDS.
    bexp(A, Env) ++ [?DUP, ?JZ, rel(length(Bc) + 1)] ++ [?DROP] ++ Bc;
%% The mirror of andthen: if the left is true the result is already on the
%% stack and the right is skipped. JZ jumps on zero, so the sense is inverted
%% with ZEQ rather than by adding a second branch opcode.
bexp({orthen, A, B}, Env) ->
    Bc = bexp(B, Env),
    bexp(A, Env) ++ [?DUP, ?ZEQ, ?JZ, rel(length(Bc) + 1)] ++ [?DROP] ++ Bc;
%% A word or a native, decided here rather than in the source: if the name is
%% one of the words in this file it is a CALL into the shared area, otherwise it
%% is an existing C function reached through its wrapper.
bexp({call, F, As}, Env) ->
    Args = lists:append([bexp(A, Env) || A <- As]),
    case maps:find(F, get(offs)) of
	{ok, _} ->
	    %% The CALLER's frame size travels with the call, because the
	    %% callee's entry is only an offset and nothing there knows how much
	    %% of the local array is already spoken for.
	    Args ++ [?CALL, {wlo, F}, {whi, F}, {frame, get(self)}];
	error ->
	    case maps:find(F, get(ni)) of
		{ok, {leaf, I}}  ->
		    case As of
			[] -> [?LIT8, 0, ?NATIVE, I];
			_  -> Args ++ [?NATIVE, I]
		    end;
		{ok, {leafn, I}} -> Args ++ [?NATIVEN, I];
		error ->
		    io:format("~s is neither a word nor a declared native.~n"
			      "  add {native, ~s, <args>, <ret>} to ~s~n",
			      [F, F, ?TERMS]),
		    halt(1)
	    end
    end.

bop(eq) -> ?EQ; bop(ne) -> ?NE; bop(lt) -> ?LT;
bop(add) -> ?ADD; bop(sub) -> ?SUB; bop(and_) -> ?AND; bop(or_) -> ?OR.
