#!/usr/bin/env escript
%% -*- erlang -*-
%%
%% Build strings.tab from strings/*.tab.src.
%%
%% One of those sources -- strings/keyword.tab.src -- is itself generated, from
%% utils/syntax.terms: every word the GRAMMAR knows (declaration keywords,
%% reserved words, operator and punctuation spellings, part names, built-in
%% function names) comes out of the same file the parser tables will come out
%% of, so the string table cannot come to hold a keyword the parser does not
%% accept, or miss one it does.
%%
%%   escript utils/gen_strings.erl emit    write strings/keyword.tab.src
%%   escript utils/gen_strings.erl merge   write strings.tab from the sources
%%   escript utils/gen_strings.erl check   verify strings.tab is up to date
%%
%% `check` is what runs in `make test`; `merge` is a developer action, so a
%% firmware build never needs Erlang.
%%
%% A NAME defined twice with the SAME literal is fine and collapses -- `in` is
%% both a declaration keyword and a reserved word, `pwm` is both a reserved word
%% and a part. Defined twice with DIFFERENT literals it is an error: that is two
%% people meaning two things by one symbol, and picking one silently is how a
%% string table starts lying.

-define(TERMS,   "utils/syntax.terms").
-define(SRCDIR,  "strings").
-define(GEN,     "strings/keyword.tab.src").
-define(TAB,     "gen/strings.tab").

main(["emit"])  -> emit(), halt(0);
main(["merge"]) -> merge(), halt(0);      % read_sources/0 emits first
main(["check"]) -> check();
main(_) ->
    io:format("usage: gen_strings.erl (emit | merge | check)~n"),
    halt(2).

%% ---------------------------------------------------------------------------
%% strings/keyword.tab.src, from the grammar
%% ---------------------------------------------------------------------------

emit() ->
    {ok, Terms} = file:consult(?TERMS),
    Rows = keyword_rows(Terms),
    Body = [[Name, " ", Lit, "\n"] || {Name, Lit} <- Rows],
    ok = file:write_file(?GEN, [header(), Body]),
    io:format("~s: ~p rows~n", [?GEN, length(Rows)]).

header() ->
    ["# generated by utils/gen_strings.erl from ", ?TERMS, " -- do not edit\n",
     "#\n",
     "# Every word the grammar knows. Edit the grammar, not this file.\n"].

%% Everything in syntax.terms that names something a user can type.  Each gives
%% a strings.tab NAME (the row's StrSym) and the literal it stands for (its
%% spelling).
%%
%% A row with no spelling contributes nothing: NEWLINE, INT, FLT, WORD and
%% T_LAST have no fixed text, and MINUS1/PLUS1 are readings the parser makes,
%% not things the scanner ever matches. They share s_null, s_MINUS and s_MOV --
%% all of which reach the table by another route.
keyword_rows(Terms) ->
    Rows =
	[{atom_to_list(Sym), atom_to_list(Sp)}
	 || {token, _E, Sp, Sym, _C, _A, _P, _As} <- Terms, Sp =/= undefined]
	++
	[{atom_to_list(Sym), atom_to_list(Sp)}
	 || {decl, _D, Sp, Sym, _C, _P} <- Terms, Sp =/= undefined]
	++
	[{atom_to_list(W), atom_to_list(W)}
	 || {parts, L} <- Terms, {W, _Part} <- L]
	++
	[{atom_to_list(W), atom_to_list(W)}
	 || {functions, L} <- Terms, {W, _Arity, _Pure} <- L],
    collapse(Rows, ?TERMS).

%% ---------------------------------------------------------------------------
%% strings.tab, from strings/*.tab.src
%% ---------------------------------------------------------------------------

merge() ->
    {Rows, Files} = read_sources(),
    ok = file:write_file(?TAB, tab_text(Rows, Files)),
    io:format("~s: ~p rows from ~p sources~n", [?TAB, length(Rows), length(Files)]).

check() ->
    {Rows, Files} = read_sources(),
    Want = iolist_to_binary(tab_text(Rows, Files)),
    case file:read_file(?TAB) of
	{ok, Want} ->
	    io:format("~s: ok -- ~p rows from ~p sources~n",
		      [?TAB, length(Rows), length(Files)]),
	    halt(0);
	{ok, Have} ->
	    io:format("~s is out of date with ~s/*.tab.src~n", [?TAB, ?SRCDIR]),
	    diff(parse_tab(Have), Rows),
	    io:format("  run: make strings~n"),
	    halt(1);
	{error, R} ->
	    io:format("~s: ~p~n", [?TAB, R]),
	    halt(1)
    end.

%% Sources merge in sorted filename order so the result does not depend on how
%% the directory happens to be laid out.  keyword.tab.src is regenerated first,
%% so `check` fails on a grammar edit too, not only on a hand edit.
read_sources() ->
    emit(),
    Files = lists:sort(filelib:wildcard(?SRCDIR ++ "/*.tab.src")),
    Rows = lists:append([rows(F) || F <- Files]),
    {collapse(Rows, ?SRCDIR), Files}.

rows(File) ->
    {ok, Bin} = file:read_file(File),
    [row(L, File) || L <- lines(Bin), keep(L)].

lines(Bin) -> string:split(binary_to_list(Bin), "\n", all).

keep([])       -> false;
keep([$# | _]) -> false;
keep(L)        -> string:trim(L) =/= "".

%% "NAME literal" -- NAME is the first whitespace-delimited word, the literal is
%% the rest of the line verbatim (it may be empty, and it may contain spaces:
%% the error texts and the /help lines are whole sentences).
row(Line, File) ->
    case string:split(Line, " ") of
	[Name, Lit] -> {Name, Lit, File};
	[Name]      -> {Name, "", File}
    end.

tab_text(Rows, Files) ->
    ["# generated by utils/gen_strings.erl -- do not edit\n",
     "#\n",
     "# Sources, merged in this order:\n",
     [["#   ", F, "\n"] || F <- Files],
     "#\n",
     "# strtab.c turns this into csp_strings.{c,h}. Order does not matter to C\n",
     "# -- every row becomes its own s_NAME[] and nothing indexes the table by\n",
     "# position -- so this file is free to follow its sources.\n",
     [[N, " ", L, "\n"] || {N, L} <- Rows]].

%% ---------------------------------------------------------------------------

%% Same NAME twice: identical literals collapse to one row, different literals
%% are an error naming both sides.
collapse(Rows, Where) ->
    lists:foldl(fun(R, Acc) -> collapse1(R, Acc, Where) end, [], Rows).

collapse1({Name, Lit}, Acc, Where) -> collapse1({Name, Lit, Where}, Acc, Where);
collapse1({Name, Lit, From}, Acc, Where) ->
    case lists:keyfind(Name, 1, Acc) of
	false ->
	    Acc ++ [{Name, Lit}];
	{Name, Lit} ->
	    Acc;
	{Name, Other} ->
	    io:format("~s: ~s defined twice, as ~p and as ~p (~s)~n",
		      [Where, Name, Other, Lit, From]),
	    halt(1)
    end.

parse_tab(Bin) ->
    [{N, L} || {N, L, _} <- [row(X, ?TAB) || X <- lines(Bin), keep(X)]].

diff(Have, Want) ->
    Only1 = [R || R <- Have, not lists:member(R, Want)],
    Only2 = [R || R <- Want, not lists:member(R, Have)],
    [io:format("  only in ~s: ~s ~p~n", [?TAB, N, L]) || {N, L} <- Only1],
    [io:format("  only in sources: ~s ~p~n", [N, L]) || {N, L} <- Only2],
    case {Only1, Only2} of
	{[], []} -> io:format("  same rows, different order~n");
	_        -> ok
    end.
