#!/bin/bash
# Emit the linker fragment that gathers the CORE objects' .rodata into one
# page-aligned section, `csp_ro`.
#
# BY OBJECT FILE, not by annotation. That is the whole reason this is a linker
# script and not a macro: a table that forgot its RODATA marker is covered too,
# and there is no eighth list to keep in step. Host-only objects are left out --
# csp_linux.c and csp_dump.c have one address space and read their own constants
# directly, which is correct there.
#
# `INSERT AFTER .rodata` is an ADDITION to the default script, not a replacement:
# nothing else about the layout has to be restated, and a toolchain update does
# not silently take a hand-copied layout with it.
#
# The trailing ALIGN pads the section out to a whole page, because mprotect works
# in pages and would otherwise take the next object's data with it.
#
# The boundary symbols are DEFINED HERE, not inherited. ld generates
# __start_/__stop_ automatically only for ORPHAN sections -- ones it placed
# itself because nothing named them. A section created by an explicit SECTIONS
# block is not an orphan, so it gets none, and the link fails with `undefined
# reference to __start_csp_ro` from the one file that needs them.
#
# __stop_ goes AFTER the padding ALIGN, so the range mprotect is handed is a
# whole number of pages.
#
# Usage:  bash utils/ro_ld.sh obj > obj/csp_ro.ld
set -eu
OBJDIR=${1:-obj}

# EXACTLY what a board links -- Makefile.board's CORE list, plus the neutral
# image. Nothing else, and getting that wrong costs time: csp_devices.o and
# csp_flash_host.o were in here at first, and they are host-only. The poison
# then fired inside csp_sector_offset walking a device table that no target ever
# compiles, which reads as a finding and is not one.
#
# The rule is simple and worth stating: poison what a BOARD would carry. A file
# that only ever runs on the host has one address space and cannot be wrong.
CORE="csp_rt csp_crc csp_line csp_repl csp_compile csp_tok csp_parse csp_print
      csp_strings csp_eeprom csp_transport csp_console csp_states csp_flash
      rom_host"

echo "/* generated by utils/ro_ld.sh -- do not edit */"
echo "SECTIONS"
echo "{"
echo "  csp_ro : ALIGN(4096)"
echo "  {"
echo "    __start_csp_ro = .;"
for o in $CORE; do
    [ -f "$OBJDIR/$o.o" ] && echo "    $OBJDIR/$o.o(.rodata .rodata.*)"
done
echo "    . = ALIGN(4096);"
echo "    __stop_csp_ro = .;"
echo "  }"
echo "}"
echo "INSERT AFTER .rodata"
